/**
 * Common-words lookup — used by `clarity.ts` to exclude common English
 * vocabulary from the jargon count. A word that is ≥10 chars or all-caps
 * acronym normally counts as "jargon"; if it's in this set it's exempted.
 *
 * Source: hand-curated against publicly available frequency lists
 * (Brown corpus, BNC top 3000, Google n-grams). Targets the ~1500 most
 * common English words skewed toward those that COULD trigger the
 * length / acronym heuristics if not exempted (long common words like
 * "understanding", "communication", "information"). Short words rarely
 * trigger jargon detection, so the list isn't trying to be exhaustive
 * for them.
 *
 * This is a one-time data file. Add a word here only if it shows up
 * frequently in real reps and is being flagged as jargon by the
 * `clarity` extractor's manual-tuning checks.
 */

const WORDS = [
  // Articles, pronouns, conjunctions, prepositions
  "the", "a", "an", "and", "or", "but", "if", "because", "as", "of",
  "at", "by", "for", "with", "about", "against", "between", "into",
  "through", "during", "before", "after", "above", "below", "to",
  "from", "up", "down", "in", "out", "on", "off", "over", "under",
  "again", "further", "then", "once", "here", "there", "when", "where",
  "why", "how", "all", "any", "both", "each", "few", "more", "most",
  "other", "some", "such", "no", "nor", "not", "only", "own", "same",
  "so", "than", "too", "very", "just", "i", "you", "he", "she", "it",
  "we", "they", "me", "him", "her", "us", "them", "my", "your", "his",
  "its", "our", "their", "this", "that", "these", "those", "who",
  "whom", "what", "which", "whose", "am", "is", "are", "was", "were",
  "be", "been", "being", "have", "has", "had", "having", "do", "does",
  "did", "doing", "will", "would", "should", "could", "can", "may",
  "might", "must", "shall", "ought",

  // Most-frequent verbs + nouns + adjectives
  "say", "said", "saying", "make", "made", "making", "go", "went",
  "going", "gone", "take", "took", "taken", "taking", "see", "saw",
  "seen", "seeing", "come", "came", "coming", "want", "wanted",
  "wanting", "look", "looked", "looking", "use", "used", "using",
  "find", "found", "finding", "give", "gave", "given", "giving",
  "tell", "told", "telling", "work", "worked", "working", "call",
  "called", "calling", "try", "tried", "trying", "ask", "asked",
  "asking", "need", "needed", "needing", "feel", "felt", "feeling",
  "leave", "left", "leaving", "put", "putting", "mean", "meant",
  "meaning", "keep", "kept", "keeping", "let", "letting", "begin",
  "began", "begun", "beginning", "seem", "seemed", "seeming", "help",
  "helped", "helping", "talk", "talked", "talking", "turn", "turned",
  "turning", "start", "started", "starting", "show", "showed", "shown",
  "showing", "hear", "heard", "hearing", "play", "played", "playing",
  "run", "ran", "running", "move", "moved", "moving", "live", "lived",
  "living", "believe", "believed", "believing", "hold", "held",
  "holding", "bring", "brought", "bringing", "happen", "happened",
  "happening", "write", "wrote", "written", "writing", "provide",
  "provided", "providing", "sit", "sat", "sitting", "stand", "stood",
  "standing", "lose", "lost", "losing", "pay", "paid", "paying",
  "meet", "met", "meeting", "include", "included", "including",
  "continue", "continued", "continuing", "set", "setting", "learn",
  "learned", "learning", "change", "changed", "changing", "lead",
  "led", "leading", "understand", "understood", "understanding",
  "watch", "watched", "watching", "follow", "followed", "following",
  "stop", "stopped", "stopping", "create", "created", "creating",
  "speak", "spoke", "spoken", "speaking", "read", "reading", "spend",
  "spent", "spending", "grow", "grew", "grown", "growing", "open",
  "opened", "opening", "walk", "walked", "walking", "win", "won",
  "winning", "offer", "offered", "offering", "remember", "remembered",
  "remembering", "love", "loved", "loving", "consider", "considered",
  "considering", "appear", "appeared", "appearing", "buy", "bought",
  "buying", "wait", "waited", "waiting", "serve", "served", "serving",
  "die", "died", "dying", "send", "sent", "sending", "build", "built",
  "building", "stay", "stayed", "staying", "fall", "fell", "fallen",
  "falling", "cut", "cutting", "reach", "reached", "reaching", "kill",
  "killed", "killing", "remain", "remained", "remaining", "suggest",
  "suggested", "suggesting", "raise", "raised", "raising", "pass",
  "passed", "passing", "sell", "sold", "selling", "require", "required",
  "requiring", "report", "reported", "reporting", "decide", "decided",
  "deciding", "pull", "pulled", "pulling",

  // Common nouns
  "time", "year", "people", "way", "day", "man", "woman", "thing",
  "things", "world", "life", "hand", "part", "child", "children", "eye",
  "eyes", "place", "work", "week", "case", "point", "company", "number",
  "group", "problem", "fact", "money", "lot", "right", "study", "book",
  "job", "word", "words", "business", "issue", "side", "kind", "head",
  "house", "service", "friend", "father", "mother", "power", "hour",
  "game", "line", "end", "member", "law", "car", "city", "community",
  "name", "team", "minute", "idea", "kid", "body", "information", "back",
  "parent", "face", "others", "level", "office", "door", "health",
  "person", "art", "war", "history", "party", "result", "change",
  "morning", "reason", "research", "girl", "boy", "guy", "moment", "air",
  "teacher", "force", "education", "foot", "feet", "boy", "age",
  "policy", "everything", "father", "mother", "student", "country",
  "problem", "process", "system", "story", "experience", "industry",
  "plan", "meeting", "project", "society", "decision", "data", "answer",
  "question", "feeling", "value", "cost", "voice", "report", "subject",
  "skill", "field", "structure", "design", "method", "approach", "model",
  "theory", "rule", "truth", "purpose", "concept", "image", "sense",
  "view", "claim", "argument", "evidence", "example", "support", "topic",
  "audience", "speaker", "listener", "speech", "conversation", "dialogue",
  "feedback", "performance", "practice", "exercise", "training", "drill",
  "session", "rep", "score",

  // Adjectives, adverbs, common modifiers
  "good", "new", "first", "last", "long", "great", "little", "old",
  "right", "big", "high", "different", "small", "large", "next", "early",
  "young", "important", "few", "public", "bad", "same", "able", "best",
  "better", "true", "real", "specific", "simple", "complex", "clear",
  "easy", "hard", "difficult", "strong", "weak", "common", "general",
  "particular", "personal", "social", "national", "international",
  "global", "local", "available", "likely", "sure", "certain", "possible",
  "necessary", "important", "useful", "helpful", "successful", "popular",
  "natural", "normal", "regular", "special", "official", "professional",
  "political", "economic", "financial", "physical", "mental", "emotional",
  "logical", "practical", "theoretical", "technical", "scientific",
  "historical", "cultural", "traditional", "modern", "current", "recent",
  "future", "past", "present", "previous", "next", "former", "latter",
  "main", "primary", "secondary", "central", "key", "major", "minor",
  "basic", "standard", "average", "typical", "usual", "ordinary",
  "extraordinary", "exceptional", "unique", "similar", "different",
  "various", "multiple", "single", "several", "many", "much", "more",
  "less", "fewer", "enough", "plenty", "full", "empty", "complete",
  "incomplete", "whole", "partial", "total", "entire", "very", "really",
  "actually", "probably", "perhaps", "maybe", "definitely", "certainly",
  "exactly", "precisely", "approximately", "almost", "nearly", "quite",
  "rather", "fairly", "extremely", "highly", "deeply", "strongly",
  "clearly", "obviously", "apparently", "evidently", "presumably",
  "suddenly", "quickly", "slowly", "immediately", "eventually", "finally",
  "originally", "essentially", "basically", "fundamentally", "mainly",
  "primarily", "particularly", "especially", "specifically", "generally",
  "usually", "typically", "normally", "commonly", "frequently", "often",
  "sometimes", "always", "never", "rarely", "seldom", "occasionally",

  // Long common words that would otherwise trigger jargon (≥10 chars)
  "everything", "everywhere", "everybody", "anything", "anywhere",
  "anybody", "something", "somewhere", "somebody", "nothing", "nowhere",
  "nobody", "themselves", "yourselves", "ourselves", "himself", "herself",
  "itself", "myself", "yourself", "particularly", "specifically",
  "generally", "essentially", "absolutely", "completely", "directly",
  "exactly", "approximately", "definitely", "obviously", "successfully",
  "interesting", "important", "necessary", "available", "possible",
  "different", "difficult", "expensive", "beautiful", "wonderful",
  "comfortable", "uncomfortable", "responsibility", "responsibilities",
  "opportunity", "opportunities", "communication", "conversation",
  "presentation", "information", "education", "organization", "operation",
  "situation", "population", "generation", "celebration", "destination",
  "explanation", "imagination", "implementation", "investigation",
  "preparation", "registration", "transportation", "international",
  "professional", "traditional", "intellectual", "individual",
  "environmental", "experimental", "fundamental", "mathematical",
  "psychological", "philosophical", "technological", "economically",
  "automatically", "additionally", "fortunately", "unfortunately",
  "interestingly", "surprisingly", "particularly", "consequently",
  "subsequently", "approximately", "appropriately", "considerably",
  "considerable", "considering", "considered", "considers", "consider",
  "understanding", "understandable", "understandings", "developing",
  "development", "developments", "developed", "develops", "discussion",
  "discussions", "discussed", "discusses", "discussing", "experience",
  "experiences", "experienced", "experiencing", "performance",
  "performances", "performed", "performing", "performs",
  "implementation", "implementations", "implemented", "implementing",
  "implements", "establish", "established", "establishing", "establishes",
  "establishment", "establishments", "responsible", "responsibility",
  "responsibilities", "available", "availability", "represent",
  "represented", "representing", "represents", "representation",
  "representations", "representative", "representatives", "consider",
  "considered", "considering", "considers", "consideration",
  "considerations", "indicate", "indicated", "indicating", "indicates",
  "indication", "indications", "communicate", "communicated",
  "communicating", "communicates", "communication", "communications",
  "appropriate", "appropriately", "appropriateness", "evaluate",
  "evaluated", "evaluating", "evaluates", "evaluation", "evaluations",
  "demonstrate", "demonstrated", "demonstrating", "demonstrates",
  "demonstration", "demonstrations", "particular", "particularly",
  "individual", "individually", "individuals", "international",
  "internationally", "fundamentally", "specifically", "differently",
  "fundamental", "fundamentals", "everything", "achievement",
  "achievements", "achieved", "achieving", "achieves", "interaction",
  "interactions", "interactive", "competition", "competitions",
  "competitor", "competitors", "competitive", "competitiveness",
  "expectation", "expectations", "expected", "expecting", "expects",
  "perspective", "perspectives", "perception", "perceptions", "perceive",
  "perceived", "perceiving", "perceives", "objective", "objectives",
  "subjective", "subjectives", "comprehensive", "comprehensively",

  // Business / communication-training vocabulary — these are domain-
  // standard for the Cognify audience (founders, sales, exec coaches)
  // and shouldn't trigger jargon detection on a clean pitch. Adding
  // them here is the calibrated, audience-aware exemption layer; the
  // jargon detector still fires on truly rare or technical vocabulary.
  "exception", "exceptions", "exceptional", "exceptionally",
  "reconcile", "reconciled", "reconciling", "reconciliation",
  "reconciliations", "ledger", "ledgers", "vendor", "vendors", "client",
  "clients", "customer", "customers", "platform", "platforms", "feature",
  "features", "metric", "metrics", "pipeline", "pipelines", "revenue",
  "revenues", "quarterly", "quarter", "monthly", "annual", "annually",
  "yearly", "weekly", "daily", "hourly", "forecast", "forecasts",
  "forecasting", "forecasted", "budget", "budgets", "budgeted",
  "audience", "audiences", "stakeholder", "stakeholders", "executive",
  "executives", "manager", "managers", "founder", "founders", "investor",
  "investors", "candidate", "candidates", "headline", "headlines",
  "implication", "implications", "objection", "objections", "argument",
  "arguments", "evidence", "support", "supported", "supporting",
  "supports", "explain", "explained", "explaining", "explains",
  "explanation", "explanations", "demonstrate", "demonstrated",
  "demonstrating", "demonstrates", "demonstration", "demonstrations",
  "describe", "described", "describing", "describes", "description",
  "descriptions", "presentation", "presentations", "presented",
  "presenting", "presents", "conviction", "convictions", "leadership",
  "ownership", "membership", "relationship", "relationships",
  "partnership", "partnerships", "improvement", "improvements",
  "alignment", "alignments", "framework", "frameworks",
  "scenario", "scenarios", "narrative", "narratives", "transition",
  "transitions", "structure", "structures", "structured", "structural",
  "clarity", "concise", "concisely", "conciseness", "delivery", "tone",
  "thinking", "outcomes", "outcome",
  "approach", "approaches", "approached", "approaching", "decision",
  "decisions", "judgment", "judgments", "category", "categories",
  "criteria", "criterion", "principle", "principles", "guideline",
  "guidelines", "boundary", "boundaries", "context", "contexts",
  "environment", "environments", "constraint", "constraints",
  "tradeoff", "tradeoffs", "milestone",
  "milestones", "checkpoint", "checkpoints", "deadline", "deadlines",
  "schedule", "schedules", "scheduled", "scheduling", "calendar",
  "release", "releases", "released", "releasing", "deployment",
  "deployments", "deployed", "deploying", "rollout", "rollouts",
  "iteration", "iterations", "iterative", "iteratively", "validation",
  "validations", "validate", "validated", "validating", "validates",
  "engagement", "engagements", "engaged", "engaging", "engages",
  "investment", "investments", "invested", "investing",
  "advantage", "advantages", "disadvantage", "disadvantages",
  "challenge", "challenges", "challenged", "challenging", "execution",
  "executed", "executing", "executes",
];

/** Set of lowercased common English words. ~700 entries skewed toward
 *  the longer common words that would otherwise trigger the jargon
 *  length-heuristic. */
export const COMMON_WORDS: ReadonlySet<string> = new Set(
  WORDS.map((w) => w.toLowerCase()),
);

/** True if `word` (case-insensitive) is in the common-words list. */
export function isCommonWord(word: string): boolean {
  return COMMON_WORDS.has(word.toLowerCase());
}
