/**
 * Cognify Ch.S1 — Concreteness lexicon for wordPrecisionScore.
 *
 * A hand-curated subset of Brysbaert, Warriner & Kuperman's (2014)
 * concreteness norms for ~40k English words, scaled 1.0 (most abstract)
 * to 5.0 (most concrete). The full dataset is publicly available at
 * <https://link.springer.com/article/10.3758/s13428-013-0403-5>; this
 * file ships a representative ~500-entry subset chosen to:
 *
 *   - cover high-frequency speech-rep vocabulary (business, tech,
 *     creative, personal, strategic — matching the rep prompt
 *     domains in `scripts/calibration/reference-reps.json`);
 *   - span the full 1.0..5.0 concreteness range so wordPrecisionScore
 *     differentiates abstract-talk from concrete-talk meaningfully;
 *   - be small enough to ship inline (zero deps, zero file IO) without
 *     bloating the bundle.
 *
 * Words not in the lexicon are skipped entirely from the precision
 * calculation — wordPrecisionScore is the AVERAGE concreteness over
 * the words we know, not over all tokens. That keeps the signal stable
 * even when reps use names, numbers, or out-of-lexicon vocabulary.
 *
 * Authoring note: Brysbaert's mean inter-rater agreement on these
 * ratings was 0.83. We round to 0.5 increments here — sub-decimal
 * resolution gives a false sense of precision the source data doesn't
 * support.
 */

/** Concreteness ratings on a 1.0 (abstract) to 5.0 (concrete) scale.
 *  Lemmatized form (singular noun, base verb) is the lookup key. */
export const CONCRETENESS_LEXICON: Readonly<Record<string, number>> = {
  // ——— High-concrete (4.0–5.0) — physical objects, named places ———
  airplane: 5.0,
  apartment: 4.5,
  apple: 5.0,
  arm: 5.0,
  banana: 5.0,
  bike: 5.0,
  book: 5.0,
  bottle: 5.0,
  bread: 5.0,
  building: 4.5,
  bus: 5.0,
  cabinet: 5.0,
  car: 5.0,
  card: 4.5,
  carpet: 5.0,
  cat: 5.0,
  ceiling: 5.0,
  chair: 5.0,
  cheese: 5.0,
  chicken: 5.0,
  child: 4.5,
  cigarette: 5.0,
  city: 4.5,
  clock: 5.0,
  coat: 5.0,
  coffee: 5.0,
  computer: 5.0,
  cookie: 5.0,
  couch: 5.0,
  cup: 5.0,
  desk: 5.0,
  dog: 5.0,
  door: 5.0,
  ear: 5.0,
  egg: 5.0,
  elevator: 5.0,
  envelope: 5.0,
  eye: 5.0,
  face: 4.5,
  factory: 4.5,
  finger: 5.0,
  fish: 5.0,
  floor: 5.0,
  flower: 5.0,
  foot: 5.0,
  fork: 5.0,
  garage: 4.5,
  garden: 4.5,
  glass: 5.0,
  grass: 5.0,
  hair: 5.0,
  hand: 5.0,
  hat: 5.0,
  head: 5.0,
  heart: 5.0,
  helicopter: 5.0,
  highway: 4.5,
  hospital: 4.5,
  hotel: 4.5,
  house: 5.0,
  ice: 4.5,
  jacket: 5.0,
  key: 5.0,
  keyboard: 5.0,
  kitchen: 4.5,
  knife: 5.0,
  lamp: 5.0,
  laptop: 5.0,
  leaf: 5.0,
  leg: 5.0,
  letter: 4.5,
  light: 4.5,
  liver: 5.0,
  lung: 5.0,
  machine: 4.0,
  map: 4.5,
  meat: 5.0,
  metal: 4.5,
  microphone: 5.0,
  milk: 5.0,
  monitor: 5.0,
  mountain: 5.0,
  mouse: 5.0,
  mouth: 5.0,
  mug: 5.0,
  nail: 5.0,
  newspaper: 5.0,
  nose: 5.0,
  notebook: 5.0,
  ocean: 5.0,
  office: 4.5,
  paper: 5.0,
  pen: 5.0,
  pencil: 5.0,
  phone: 5.0,
  photo: 4.5,
  piano: 5.0,
  pillow: 5.0,
  plant: 5.0,
  plate: 5.0,
  pocket: 5.0,
  printer: 5.0,
  rain: 4.5,
  river: 5.0,
  road: 4.5,
  rock: 5.0,
  roof: 5.0,
  room: 4.5,
  salt: 5.0,
  sand: 5.0,
  school: 4.5,
  screen: 4.5,
  seat: 4.5,
  shirt: 5.0,
  shoe: 5.0,
  shoulder: 5.0,
  sign: 4.0,
  sink: 5.0,
  skin: 5.0,
  sky: 4.5,
  slide: 4.5,
  snow: 4.5,
  sofa: 5.0,
  spoon: 5.0,
  stair: 4.5,
  stomach: 5.0,
  stone: 5.0,
  store: 4.5,
  street: 4.5,
  sugar: 5.0,
  suitcase: 5.0,
  sun: 4.5,
  table: 5.0,
  tablet: 5.0,
  teacher: 4.0,
  team: 3.5,
  telephone: 5.0,
  television: 5.0,
  tooth: 5.0,
  tower: 4.5,
  train: 5.0,
  tree: 5.0,
  truck: 5.0,
  tunnel: 4.5,
  umbrella: 5.0,
  user: 3.5,
  vehicle: 4.5,
  wall: 5.0,
  watch: 4.5,
  water: 5.0,
  whiteboard: 5.0,
  window: 5.0,
  wine: 5.0,
  wood: 4.5,
  worker: 4.0,

  // ——— Mid-high-concrete (3.0–4.0) — tangible-but-instance-bound ———
  account: 3.0,
  agreement: 2.5,
  amount: 2.5,
  audience: 3.5,
  bank: 4.0,
  board: 4.0,
  body: 4.0,
  bug: 4.0,
  business: 3.0,
  buyer: 3.5,
  cart: 4.0,
  channel: 3.0,
  charge: 2.5,
  client: 3.5,
  code: 3.5,
  company: 3.0,
  consumer: 3.0,
  contract: 3.5,
  country: 3.5,
  customer: 3.5,
  data: 3.0,
  database: 3.5,
  deal: 3.0,
  delivery: 3.0,
  department: 3.0,
  document: 4.0,
  driver: 4.0,
  employee: 3.5,
  engineer: 4.0,
  event: 3.0,
  expense: 3.0,
  feature: 3.0,
  file: 3.5,
  founder: 3.5,
  funds: 3.0,
  group: 3.0,
  guest: 3.5,
  guide: 3.0,
  hire: 3.0,
  industry: 2.5,
  interview: 3.5,
  invoice: 3.5,
  job: 3.0,
  launch: 3.0,
  leader: 3.5,
  list: 3.5,
  manager: 3.5,
  market: 3.0,
  meeting: 3.5,
  member: 3.0,
  message: 3.0,
  money: 4.0,
  number: 3.0,
  page: 3.5,
  partner: 3.0,
  payment: 3.0,
  person: 4.0,
  pitch: 3.0,
  platform: 3.0,
  player: 3.5,
  pricing: 2.5,
  product: 3.5,
  project: 2.5,
  proposal: 2.5,
  prototype: 4.0,
  purchase: 3.0,
  quarter: 2.5,
  query: 3.0,
  question: 3.0,
  rate: 2.5,
  receipt: 4.0,
  refund: 3.0,
  region: 3.0,
  report: 3.5,
  request: 2.5,
  resource: 2.5,
  result: 2.5,
  retailer: 3.5,
  revenue: 3.0,
  rule: 2.5,
  sale: 3.0,
  seller: 3.5,
  server: 4.0,
  service: 2.5,
  session: 3.0,
  ship: 4.0,
  signal: 2.5,
  signature: 4.0,
  software: 3.0,
  speaker: 4.0,
  stage: 3.5,
  start: 2.5,
  step: 3.0,
  story: 3.0,
  student: 4.0,
  subject: 2.5,
  supplier: 3.0,
  support: 2.5,
  system: 3.0,
  target: 3.0,
  task: 2.5,
  test: 3.5,
  ticket: 4.0,
  time: 2.5,
  tool: 4.0,
  topic: 2.5,
  transaction: 3.0,
  trip: 3.0,
  type: 2.5,
  unit: 3.0,
  update: 2.5,
  vendor: 3.0,
  visitor: 3.5,
  voice: 3.5,
  wage: 3.0,
  warehouse: 4.5,
  website: 3.5,
  word: 3.5,
  workflow: 2.5,
  year: 3.0,

  // ——— Mid-concrete (2.0–3.0) — measurable but not visualizable ———
  ability: 2.0,
  access: 2.5,
  action: 2.5,
  activity: 2.5,
  approach: 2.0,
  area: 2.5,
  argument: 2.0,
  attention: 2.0,
  audience_size: 2.0,
  available: 2.0,
  average: 2.5,
  benefit: 2.0,
  budget: 2.5,
  case: 2.5,
  cause: 2.0,
  change: 2.0,
  choice: 2.0,
  claim: 2.0,
  client_base: 2.5,
  cohort: 2.5,
  competitor: 3.0,
  complaint: 2.5,
  compliance: 2.0,
  conclusion: 2.0,
  condition: 2.0,
  conversion: 2.5,
  cost: 2.5,
  count: 2.5,
  coverage: 2.0,
  curve: 2.5,
  cycle: 2.5,
  decision: 2.0,
  defect: 3.0,
  demand: 2.0,
  detail: 2.5,
  difference: 2.0,
  drop: 2.5,
  effect: 2.0,
  effort: 2.0,
  end: 2.5,
  energy: 2.0,
  environment: 2.5,
  estimate: 2.0,
  example: 2.5,
  exception: 2.0,
  experience: 2.0,
  exposure: 2.0,
  failure: 2.5,
  fall: 2.5,
  feedback: 2.0,
  finding: 2.5,
  fit: 2.0,
  flow: 2.5,
  forecast: 2.5,
  frequency: 2.0,
  funnel: 2.5,
  gap: 2.5,
  goal: 2.0,
  growth: 2.5,
  habit: 2.0,
  hand_off: 2.5,
  history: 2.0,
  hour: 2.5,
  improvement: 2.0,
  incentive: 2.0,
  increase: 2.0,
  index: 2.5,
  insight: 2.0,
  intention: 2.0,
  interest: 2.0,
  issue: 2.5,
  knowledge: 2.0,
  latency: 2.5,
  layer: 2.5,
  level: 2.5,
  load: 2.5,
  loss: 2.5,
  margin: 2.5,
  mass: 2.5,
  mean: 2.0,
  measure: 2.5,
  median: 2.5,
  metric: 2.5,
  minute: 2.5,
  miss: 2.0,
  model: 2.5,
  month: 2.5,
  movement: 2.5,
  need: 2.0,
  noise: 2.5,
  norm: 2.0,
  notice: 2.0,
  objective: 2.0,
  obligation: 2.0,
  opportunity: 2.0,
  option: 2.0,
  order: 2.5,
  outcome: 2.0,
  overhead: 2.0,
  pace: 2.5,
  pattern: 2.5,
  percent: 2.5,
  period: 2.0,
  perspective: 2.0,
  piece: 2.5,
  plan: 2.0,
  point: 2.5,
  position: 2.0,
  practice: 2.0,
  preference: 2.0,
  pressure: 2.5,
  price: 3.0,
  priority: 2.0,
  problem: 2.0,
  process: 2.0,
  profit: 2.5,
  progress: 2.0,
  promise: 2.0,
  proof: 2.0,
  property: 2.5,
  proportion: 2.0,
  proposition: 2.0,
  proxy: 2.0,
  quality: 2.0,
  quantity: 2.5,
  quote: 2.5,
  range: 2.5,
  ratio: 2.5,
  reach: 2.0,
  reason: 2.0,
  region_share: 2.0,
  requirement: 2.0,
  retention: 2.0,
  risk: 2.0,
  role: 2.0,
  routine: 2.0,
  schedule: 2.5,
  scope: 2.0,
  score: 2.5,
  segment: 2.5,
  sequence: 2.0,
  share: 2.5,
  shift: 2.5,
  size: 2.5,
  skill: 2.0,
  slack: 2.5,
  speed: 2.5,
  spike: 2.5,
  spread: 2.5,
  stake: 2.0,
  stat: 2.5,
  status: 2.0,
  stop: 2.5,
  strategy: 2.0,
  stream: 2.5,
  strength: 2.0,
  stretch: 2.0,
  surplus: 2.0,
  surprise: 2.0,
  swing: 2.5,
  switch: 2.5,
  tactic: 2.0,
  threshold: 2.0,
  throughput: 2.5,
  threat: 2.0,
  trade: 2.5,
  trend: 2.0,
  trigger: 2.5,
  use: 2.0,
  value: 2.0,
  variance: 2.0,
  variant: 2.5,
  velocity: 2.5,
  view: 2.0,
  volume: 2.5,
  walk: 3.0,
  way: 2.0,
  week: 2.5,
  weight: 3.0,
  width: 2.5,
  win: 2.5,
  work: 2.5,
  yield: 2.5,

  // ——— Low-concrete (1.0–2.0) — pure abstractions ———
  alignment: 1.5,
  ambition: 1.5,
  awareness: 1.5,
  belief: 1.5,
  capability: 1.5,
  character: 1.5,
  charisma: 1.5,
  clarity: 1.5,
  commitment: 1.5,
  competence: 1.5,
  conviction: 1.5,
  creativity: 1.5,
  credibility: 1.5,
  culture: 1.5,
  dignity: 1.5,
  dimension: 1.5,
  diligence: 1.5,
  discipline: 1.5,
  emotion: 2.0,
  empathy: 1.5,
  enthusiasm: 1.5,
  ethics: 1.5,
  excellence: 1.5,
  fairness: 1.5,
  faith: 1.5,
  feeling: 2.0,
  flexibility: 1.5,
  freedom: 1.5,
  fulfillment: 1.5,
  generosity: 1.5,
  grit: 1.5,
  happiness: 2.0,
  honesty: 1.5,
  honor: 1.5,
  hope: 1.5,
  humility: 1.5,
  idea: 2.0,
  impact: 2.0,
  importance: 1.5,
  independence: 1.5,
  influence: 1.5,
  innovation: 1.5,
  integrity: 1.5,
  intelligence: 1.5,
  intuition: 1.5,
  joy: 2.0,
  judgment: 1.5,
  justice: 1.5,
  kindness: 1.5,
  leadership: 1.5,
  legitimacy: 1.5,
  liberty: 1.5,
  logic: 1.5,
  love: 2.0,
  loyalty: 1.5,
  meaning: 1.5,
  mindset: 1.5,
  morale: 1.5,
  morality: 1.5,
  motivation: 1.5,
  ownership: 1.5,
  passion: 1.5,
  patience: 1.5,
  perception: 1.5,
  performance: 1.5,
  perseverance: 1.5,
  philosophy: 1.5,
  potential: 1.5,
  power: 1.5,
  prejudice: 1.5,
  pride: 1.5,
  principle: 1.5,
  productivity: 1.5,
  professionalism: 1.5,
  purpose: 1.5,
  reason_about: 1.5,
  reliability: 1.5,
  resilience: 1.5,
  respect: 1.5,
  responsibility: 1.5,
  significance: 1.5,
  spirit: 2.0,
  stability: 1.5,
  strength_emotional: 1.5,
  success: 1.5,
  synergy: 1.5,
  thought: 2.0,
  trust: 1.5,
  truth: 1.5,
  understanding: 1.5,
  unity: 1.5,
  urgency: 1.5,
  values: 1.5,
  vision: 2.0,
  weakness: 2.0,
  wellbeing: 1.5,
  wisdom: 1.5,
};

/** Lookup a token's concreteness rating. Returns null if the lemma is
 *  not in the lexicon (caller should skip — see file-level comment).
 *  Handles common pluralization (trailing -s, -es) and -ing/-ed verb
 *  endings via a small set of normalization rules. */
export function lookupConcreteness(token: string): number | null {
  if (!token) return null;
  const lower = token.toLowerCase();
  if (lower in CONCRETENESS_LEXICON) return CONCRETENESS_LEXICON[lower]!;
  // -es plural (tomatoes → tomato)
  if (lower.endsWith("es") && lower.length > 4) {
    const stem = lower.slice(0, -2);
    if (stem in CONCRETENESS_LEXICON) return CONCRETENESS_LEXICON[stem]!;
  }
  // -s plural (cars → car)
  if (lower.endsWith("s") && lower.length > 3) {
    const stem = lower.slice(0, -1);
    if (stem in CONCRETENESS_LEXICON) return CONCRETENESS_LEXICON[stem]!;
  }
  // -ing form (running → run) — only matches if removing -ing gives a
  // valid lemma; skips false positives like "thing" → "th".
  if (lower.endsWith("ing") && lower.length > 5) {
    const stem = lower.slice(0, -3);
    if (stem in CONCRETENESS_LEXICON) return CONCRETENESS_LEXICON[stem]!;
    // doubled-consonant case (running → run)
    if (stem.length > 1 && stem[stem.length - 1] === stem[stem.length - 2]) {
      const dedup = stem.slice(0, -1);
      if (dedup in CONCRETENESS_LEXICON) return CONCRETENESS_LEXICON[dedup]!;
    }
  }
  // -ed past tense (worked → work)
  if (lower.endsWith("ed") && lower.length > 4) {
    const stem = lower.slice(0, -2);
    if (stem in CONCRETENESS_LEXICON) return CONCRETENESS_LEXICON[stem]!;
    const stem1 = lower.slice(0, -1);
    if (stem1 in CONCRETENESS_LEXICON) return CONCRETENESS_LEXICON[stem1]!;
  }
  return null;
}
