import type { VerticalId } from "@/lib/onboarding/constants";
import type { VerticalPrompt } from "./types";

/**
 * Vertical prompt bank — real-world scenarios organized by vertical.
 *
 * Used by the Build a Rep flow (Phase 5) to show 5 vertical-appropriate
 * prompts based on the user's onboarding selection. Per the team spec,
 * Build a Rep prompts ARE vertical-specific — the opposite rule from
 * Daily Workout which uses general prompts.
 *
 * Stored as `VerticalPrompt` objects with stable `id`. The optional
 * `stakeholder` field is left undefined here; expansion-pass prompts
 * populate it (drawn from VERTICALS[id].stakeholders) so the picker can
 * stratify by counterpart and avoid a slate of five "explain to your
 * client" prompts.
 */

export const VERTICAL_PROMPTS: Record<VerticalId, readonly VerticalPrompt[]> = {
  sales: [
    { id: "sales_001", vertical: "sales", text: "Explain the value of your product clearly to a skeptical buyer" },
    { id: "sales_002", vertical: "sales", text: "Respond to a pricing objection without dropping your price" },
    { id: "sales_003", vertical: "sales", text: "Walk through a discovery call recap with a stakeholder" },
    { id: "sales_004", vertical: "sales", text: "Summarize ROI to a buyer in under 60 seconds" },
    { id: "sales_005", vertical: "sales", text: "Pitch your solution concisely to a distracted executive" },
    { id: "sales_006", vertical: "sales", text: "Handle a 'we already have a vendor' objection" },
    { id: "sales_007", vertical: "sales", text: "Open a cold call that gets a yes to a 15-minute meeting" },
    { id: "sales_008", vertical: "sales", text: "Explain why your product is worth the price premium" },
    { id: "sales_009", vertical: "sales", text: "Respond to 'send me more info and I'll get back to you'" },
    { id: "sales_010", vertical: "sales", text: "Deliver a case study that lands in 30 seconds" },
    { id: "sales_011", vertical: "sales", text: "Ask a discovery question that uncovers a real pain point" },
    { id: "sales_012", vertical: "sales", text: "Explain your competitive differentiator without trash-talking" },
    { id: "sales_013", vertical: "sales", text: "Handle a CFO asking 'what's the hard ROI?'" },
    { id: "sales_014", vertical: "sales", text: "Defend your product against a lower-priced alternative" },
    { id: "sales_015", vertical: "sales", text: "Respond to 'we don't have budget for this'" },
    { id: "sales_016", vertical: "sales", stakeholder: "Economic buyer", text: "Open a discovery call with a CFO who's already skeptical of the category" },
    { id: "sales_017", vertical: "sales", stakeholder: "Champion / end user", text: "Coach your champion on how to defend the deal internally without you in the room" },
    { id: "sales_018", vertical: "sales", stakeholder: "Procurement lead", text: "Negotiate around a procurement gate that's holding the deal in legal review" },
    { id: "sales_019", vertical: "sales", stakeholder: "VP of Sales", text: "Brief your VP on a deal that's slipping a quarter — without minimizing the slip" },
    { id: "sales_020", vertical: "sales", stakeholder: "Solutions engineer", text: "Hand off a buyer to your SE without losing momentum on the call" },
    { id: "sales_021", vertical: "sales", stakeholder: "Director of Revenue", text: "Defend a discount you gave to your director of revenue" },
    { id: "sales_022", vertical: "sales", stakeholder: "Skeptical prospect", text: "Re-engage a prospect who ghosted you for 90 days" },
    { id: "sales_023", vertical: "sales", stakeholder: "Economic buyer", text: "Get a CFO to take a 15-minute follow-up after a flat first meeting" },
    { id: "sales_024", vertical: "sales", stakeholder: "Champion / end user", text: "Help an internal champion build the business case in their language" },
    { id: "sales_025", vertical: "sales", stakeholder: "Sales manager", text: "Tell your manager why you're pulling out of a deal that looked locked" },
    { id: "sales_026", vertical: "sales", stakeholder: "Solutions engineer", text: "Walk a customer through your product without slipping into a feature dump" },
    { id: "sales_027", vertical: "sales", stakeholder: "Skeptical prospect", text: "Respond to 'this isn't a priority for us right now'" },
    { id: "sales_028", vertical: "sales", stakeholder: "Procurement lead", text: "Push back on a procurement-driven price reduction without losing the deal" },
    { id: "sales_029", vertical: "sales", stakeholder: "Economic buyer", text: "Pitch ROI to a CFO who only believes hard numbers" },
    { id: "sales_030", vertical: "sales", stakeholder: "VP of Sales", text: "Tell your VP why a forecast slipped — own the part you can" },
    { id: "sales_031", vertical: "sales", stakeholder: "Champion / end user", text: "Coach a champion on how to brief their VP in 90 seconds" },
    { id: "sales_032", vertical: "sales", stakeholder: "Director of Revenue", text: "Pitch a strategic partnership to your director of revenue" },
    { id: "sales_033", vertical: "sales", stakeholder: "Skeptical prospect", text: "Respond to 'I've heard horror stories about your company'" },
    { id: "sales_034", vertical: "sales", stakeholder: "Solutions engineer", text: "Bring your SE up to speed on a customer's hidden technical concern" },
    { id: "sales_035", vertical: "sales", stakeholder: "Economic buyer", text: "Open a meeting with a CRO who has 12 minutes" },
    { id: "sales_036", vertical: "sales", stakeholder: "Procurement lead", text: "Walk procurement through your security and compliance posture" },
    { id: "sales_037", vertical: "sales", stakeholder: "Champion / end user", text: "Coach your champion on a stakeholder you've never met but they have to convince" },
    { id: "sales_038", vertical: "sales", stakeholder: "Sales manager", text: "Talk to your manager about quota relief mid-quarter" },
    { id: "sales_039", vertical: "sales", stakeholder: "Skeptical prospect", text: "Respond to 'we'll just build this internally'" },
    { id: "sales_040", vertical: "sales", stakeholder: "Economic buyer", text: "Re-pitch a CFO who said no six months ago" },
    { id: "sales_041", vertical: "sales", stakeholder: "VP of Sales", text: "Pitch your VP on dropping a market segment that's draining your team" },
    { id: "sales_042", vertical: "sales", stakeholder: "Solutions engineer", text: "Coordinate a 30-minute technical deep-dive with your SE on the line" },
    { id: "sales_043", vertical: "sales", stakeholder: "Skeptical prospect", text: "Respond to 'your competitor just gave us a quote that's 30% cheaper'" },
    { id: "sales_044", vertical: "sales", stakeholder: "Champion / end user", text: "Coach a champion on how to push back on their own CFO" },
    { id: "sales_045", vertical: "sales", stakeholder: "Procurement lead", text: "Get procurement to fast-track your renewal" },
    { id: "sales_046", vertical: "sales", stakeholder: "Economic buyer", text: "Convince a CEO that your tool unlocks a metric they actually care about" },
    { id: "sales_047", vertical: "sales", stakeholder: "Sales manager", text: "Brief your manager on a competitor that's quietly winning your accounts" },
    { id: "sales_048", vertical: "sales", stakeholder: "Skeptical prospect", text: "Respond to 'send us a deck and we'll discuss internally'" },
    { id: "sales_049", vertical: "sales", stakeholder: "Champion / end user", text: "Coach a junior champion on selling to a senior stakeholder" },
    { id: "sales_050", vertical: "sales", stakeholder: "Economic buyer", text: "Open a renewal conversation with a CFO who's looking for cuts" },
  ],
  consulting: [
    { id: "consulting_001", vertical: "consulting", text: "Present a recommendation to a client CFO" },
    { id: "consulting_002", vertical: "consulting", text: "Defend your analysis under pointed pushback" },
    { id: "consulting_003", vertical: "consulting", text: "Explain your analytical approach to a non-analyst" },
    { id: "consulting_004", vertical: "consulting", text: "Walk through your reasoning for a strategic choice" },
    { id: "consulting_005", vertical: "consulting", text: "Communicate a counterintuitive insight clearly" },
    { id: "consulting_006", vertical: "consulting", text: "Explain why the client's current approach isn't working" },
    { id: "consulting_007", vertical: "consulting", text: "Deliver bad news that the client will thank you for later" },
    { id: "consulting_008", vertical: "consulting", text: "Present three options and make the case for one" },
    { id: "consulting_009", vertical: "consulting", text: "Explain a framework to a client unfamiliar with it" },
    { id: "consulting_010", vertical: "consulting", text: "Handle a client who disagrees with your recommendation" },
    { id: "consulting_011", vertical: "consulting", text: "Tell a client their favorite initiative should be killed" },
    { id: "consulting_012", vertical: "consulting", text: "Walk an executive through a complex model in 90 seconds" },
    { id: "consulting_013", vertical: "consulting", text: "Explain a risk without sounding alarmist" },
    { id: "consulting_014", vertical: "consulting", text: "Defend a recommendation against political pushback" },
    { id: "consulting_015", vertical: "consulting", text: "Translate a quantitative insight into a strategic decision" },
    { id: "consulting_016", vertical: "consulting", stakeholder: "Client executive sponsor", text: "Open a steering committee meeting with bad news the client doesn't want to hear" },
    { id: "consulting_017", vertical: "consulting", stakeholder: "Partner / managing director", text: "Brief your partner on a recommendation they're going to push back on" },
    { id: "consulting_018", vertical: "consulting", stakeholder: "IT director", text: "Convince an IT director that your tooling change is worth the migration risk" },
    { id: "consulting_019", vertical: "consulting", stakeholder: "Change-management lead", text: "Coach the change lead on framing the rollout to a resistant team" },
    { id: "consulting_020", vertical: "consulting", stakeholder: "End-user working group", text: "Run a workshop where half the room thinks the project shouldn't happen" },
    { id: "consulting_021", vertical: "consulting", stakeholder: "Project steering committee", text: "Walk a steering committee through three scenarios and recommend one" },
    { id: "consulting_022", vertical: "consulting", stakeholder: "Client executive sponsor", text: "Tell a client sponsor that the timeline they sold internally is impossible" },
    { id: "consulting_023", vertical: "consulting", stakeholder: "Partner / managing director", text: "Tell your partner you want to walk away from the engagement" },
    { id: "consulting_024", vertical: "consulting", stakeholder: "End-user working group", text: "Defend a controversial process change to the people who'll have to live it" },
    { id: "consulting_025", vertical: "consulting", stakeholder: "Project steering committee", text: "Present three options where two are obviously worse to set up the right call" },
    { id: "consulting_026", vertical: "consulting", stakeholder: "IT director", text: "Walk an IT director through your security model under heavy scrutiny" },
    { id: "consulting_027", vertical: "consulting", stakeholder: "Client executive sponsor", text: "Tell a sponsor their pet initiative is in your kill list" },
    { id: "consulting_028", vertical: "consulting", stakeholder: "Change-management lead", text: "Brief a change lead on the people who'll need extra coaching" },
    { id: "consulting_029", vertical: "consulting", stakeholder: "Partner / managing director", text: "Push back on your MD's framing of the client's actual problem" },
    { id: "consulting_030", vertical: "consulting", stakeholder: "Client executive sponsor", text: "Walk a sponsor through a recommendation that affects their own role" },
    { id: "consulting_031", vertical: "consulting", stakeholder: "Project steering committee", text: "Defend the analytical rigor of a study under tough committee questioning" },
    { id: "consulting_032", vertical: "consulting", stakeholder: "End-user working group", text: "Translate a strategic recommendation into what end users will actually do differently" },
    { id: "consulting_033", vertical: "consulting", stakeholder: "Partner / managing director", text: "Pitch your partner on staffing a junior on a high-visibility account" },
    { id: "consulting_034", vertical: "consulting", stakeholder: "IT director", text: "Walk an IT director through a phased migration plan they'll have to defend" },
    { id: "consulting_035", vertical: "consulting", stakeholder: "Client executive sponsor", text: "Open a meeting where the client thinks consulting hasn't earned its fee" },
    { id: "consulting_036", vertical: "consulting", stakeholder: "Project steering committee", text: "Recommend canceling a steering committee's flagship project" },
    { id: "consulting_037", vertical: "consulting", stakeholder: "End-user working group", text: "Field tough questions from end users about why their team was reorganized" },
    { id: "consulting_038", vertical: "consulting", stakeholder: "Change-management lead", text: "Push back on the change lead's communication plan" },
    { id: "consulting_039", vertical: "consulting", stakeholder: "Partner / managing director", text: "Tell your MD a key client is about to fire your firm" },
    { id: "consulting_040", vertical: "consulting", stakeholder: "Client executive sponsor", text: "Defend a recommendation that ran into political resistance from a peer department" },
    { id: "consulting_041", vertical: "consulting", stakeholder: "IT director", text: "Negotiate scope with an IT director who keeps adding requirements" },
    { id: "consulting_042", vertical: "consulting", stakeholder: "End-user working group", text: "Coach a working group on a workflow change that doubles their work in week one" },
    { id: "consulting_043", vertical: "consulting", stakeholder: "Project steering committee", text: "Walk a steering committee through a model whose assumptions just got invalidated" },
    { id: "consulting_044", vertical: "consulting", stakeholder: "Partner / managing director", text: "Pitch your partner on a pro-bono engagement they'll instinctively reject" },
    { id: "consulting_045", vertical: "consulting", stakeholder: "Client executive sponsor", text: "Walk a sponsor through a recommendation that effectively cuts their team in half" },
    { id: "consulting_046", vertical: "consulting", stakeholder: "Change-management lead", text: "Tell the change lead the rollout cadence they planned is too aggressive" },
    { id: "consulting_047", vertical: "consulting", stakeholder: "End-user working group", text: "Lead a workshop with a working group that just had their senior leader replaced" },
    { id: "consulting_048", vertical: "consulting", stakeholder: "Partner / managing director", text: "Tell your partner the client is asking for work outside the engagement scope" },
    { id: "consulting_049", vertical: "consulting", stakeholder: "Client executive sponsor", text: "Recommend a vendor switch to a sponsor who personally championed the current vendor" },
    { id: "consulting_050", vertical: "consulting", stakeholder: "Project steering committee", text: "Defend a budget overrun to a steering committee that warned you about it" },
  ],
  finance: [
    { id: "finance_001", vertical: "finance", text: "Explain Q3 results to non-financial executives" },
    { id: "finance_002", vertical: "finance", text: "Justify a proposed investment to the board" },
    { id: "finance_003", vertical: "finance", text: "Present insights from last month's performance" },
    { id: "finance_004", vertical: "finance", text: "Walk through key metrics in under 60 seconds" },
    { id: "finance_005", vertical: "finance", text: "Explain a tradeoff between short-term and long-term spend" },
    { id: "finance_006", vertical: "finance", text: "Defend a budget variance to a skeptical manager" },
    { id: "finance_007", vertical: "finance", text: "Explain why margins compressed this quarter" },
    { id: "finance_008", vertical: "finance", text: "Present a sensitivity analysis to a non-technical audience" },
    { id: "finance_009", vertical: "finance", text: "Explain a forecasting change to the CEO" },
    { id: "finance_010", vertical: "finance", text: "Justify headcount for a team you're growing" },
    { id: "finance_011", vertical: "finance", text: "Explain a cash flow concern to a founder" },
    { id: "finance_012", vertical: "finance", text: "Walk through a capital allocation decision" },
    { id: "finance_013", vertical: "finance", text: "Translate a finance insight into an operational action" },
    { id: "finance_014", vertical: "finance", text: "Explain why you're recommending against a buyback" },
    { id: "finance_015", vertical: "finance", text: "Present a risk the board hasn't yet noticed" },
    { id: "finance_016", vertical: "finance", stakeholder: "CFO", text: "Walk your CFO through a forecast revision the team won't like" },
    { id: "finance_017", vertical: "finance", stakeholder: "Investment committee", text: "Defend an investment thesis the committee has already voted down once" },
    { id: "finance_018", vertical: "finance", stakeholder: "Board member", text: "Brief a board member on a risk you've been quietly tracking" },
    { id: "finance_019", vertical: "finance", stakeholder: "Portfolio manager", text: "Pitch a deal to a PM who's already at capacity" },
    { id: "finance_020", vertical: "finance", stakeholder: "MD / partner", text: "Walk an MD through a model they're skeptical of" },
    { id: "finance_021", vertical: "finance", stakeholder: "External auditor", text: "Walk an auditor through a control failure you self-reported" },
    { id: "finance_022", vertical: "finance", stakeholder: "Equity analyst", text: "Walk a sell-side analyst through a guidance change without spooking them" },
    { id: "finance_023", vertical: "finance", stakeholder: "VP / director", text: "Pitch your director on hiring an FP&A analyst they don't think you need" },
    { id: "finance_024", vertical: "finance", stakeholder: "Client / LP", text: "Tell an LP why a fund returned below benchmark this year" },
    { id: "finance_025", vertical: "finance", stakeholder: "CFO", text: "Recommend an unconventional capital structure to your CFO" },
    { id: "finance_026", vertical: "finance", stakeholder: "Investment committee", text: "Withdraw a recommendation mid-meeting after one new piece of data" },
    { id: "finance_027", vertical: "finance", stakeholder: "Board member", text: "Walk a board member through their first close-up of a quarterly close" },
    { id: "finance_028", vertical: "finance", stakeholder: "MD / partner", text: "Defend your model's assumption to an MD who builds them for a living" },
    { id: "finance_029", vertical: "finance", stakeholder: "Portfolio manager", text: "Update a PM that a position is suddenly losing money fast" },
    { id: "finance_030", vertical: "finance", stakeholder: "External auditor", text: "Walk an auditor through how revenue gets recognized in your hardest contract" },
    { id: "finance_031", vertical: "finance", stakeholder: "VP / director", text: "Tell your director the budget process needs to change next cycle" },
    { id: "finance_032", vertical: "finance", stakeholder: "CFO", text: "Walk your CFO through why margins compressed despite higher revenue" },
    { id: "finance_033", vertical: "finance", stakeholder: "Equity analyst", text: "Defend an unusual segment classification to a sell-side analyst" },
    { id: "finance_034", vertical: "finance", stakeholder: "Investment committee", text: "Make a case for an investment that's outside the fund's normal mandate" },
    { id: "finance_035", vertical: "finance", stakeholder: "Client / LP", text: "Brief an LP on why fees aren't being reduced this year" },
    { id: "finance_036", vertical: "finance", stakeholder: "Board member", text: "Walk a board member through your firm's biggest unhedged risk" },
    { id: "finance_037", vertical: "finance", stakeholder: "Portfolio manager", text: "Tell a PM that a name they own is about to take a write-down" },
    { id: "finance_038", vertical: "finance", stakeholder: "MD / partner", text: "Tell your MD the deal you've been working will fall apart this week" },
    { id: "finance_039", vertical: "finance", stakeholder: "External auditor", text: "Defend an estimate the auditor wants to challenge" },
    { id: "finance_040", vertical: "finance", stakeholder: "VP / director", text: "Walk your VP through why a forecast you signed off on is now wrong" },
    { id: "finance_041", vertical: "finance", stakeholder: "CFO", text: "Defend the cost of a finance system upgrade to your CFO" },
    { id: "finance_042", vertical: "finance", stakeholder: "Equity analyst", text: "Brief an analyst on what's NOT in the press release that they should care about" },
    { id: "finance_043", vertical: "finance", stakeholder: "Investment committee", text: "Open a committee meeting on a deal where the lead deal team disagrees with you" },
    { id: "finance_044", vertical: "finance", stakeholder: "Client / LP", text: "Walk an LP through a side letter ask you can't accommodate" },
    { id: "finance_045", vertical: "finance", stakeholder: "Board member", text: "Recommend a CEO compensation change to the board comp committee" },
    { id: "finance_046", vertical: "finance", stakeholder: "Portfolio manager", text: "Get a PM to consider a position they previously rejected" },
    { id: "finance_047", vertical: "finance", stakeholder: "MD / partner", text: "Tell your MD that a senior banker on the deal isn't pulling their weight" },
    { id: "finance_048", vertical: "finance", stakeholder: "External auditor", text: "Address an auditor's question about a related-party transaction" },
    { id: "finance_049", vertical: "finance", stakeholder: "VP / director", text: "Pitch your VP on a budget reallocation that helps your team and hurts a peer's" },
    { id: "finance_050", vertical: "finance", stakeholder: "CFO", text: "Walk your CFO through a leveraged transaction's worst-case scenario" },
  ],
  healthcare: [
    { id: "healthcare_001", vertical: "healthcare", text: "Explain a diagnosis to a patient who's scared" },
    { id: "healthcare_002", vertical: "healthcare", text: "Recommend a treatment plan to a skeptical patient" },
    { id: "healthcare_003", vertical: "healthcare", text: "Handle concerns from a patient's family member" },
    { id: "healthcare_004", vertical: "healthcare", text: "Break down a medical condition in plain language" },
    { id: "healthcare_005", vertical: "healthcare", text: "Guide a patient through the next steps in their care" },
    { id: "healthcare_006", vertical: "healthcare", text: "Explain side effects without minimizing them" },
    { id: "healthcare_007", vertical: "healthcare", text: "Discuss a change in treatment plan with a patient" },
    { id: "healthcare_008", vertical: "healthcare", text: "Deliver a difficult prognosis with compassion" },
    { id: "healthcare_009", vertical: "healthcare", text: "Explain lab results to a patient without medical background" },
    { id: "healthcare_010", vertical: "healthcare", text: "Handoff a patient to a colleague during shift change" },
    { id: "healthcare_011", vertical: "healthcare", text: "Respond to a patient refusing a recommended treatment" },
    { id: "healthcare_012", vertical: "healthcare", text: "Explain a procedure to reduce pre-op anxiety" },
    { id: "healthcare_013", vertical: "healthcare", text: "Present a case to an attending physician" },
    { id: "healthcare_014", vertical: "healthcare", text: "Discuss lifestyle changes without sounding preachy" },
    { id: "healthcare_015", vertical: "healthcare", text: "Explain a medication regimen so it actually gets followed" },
    { id: "healthcare_016", vertical: "healthcare", stakeholder: "Patient", text: "Tell a patient their imaging shows something concerning that needs follow-up" },
    { id: "healthcare_017", vertical: "healthcare", stakeholder: "Family member / caregiver", text: "Speak with the spouse of a patient who is no longer competent to consent" },
    { id: "healthcare_018", vertical: "healthcare", stakeholder: "Attending physician", text: "Present a case that was bumped from yesterday's rounds for review today" },
    { id: "healthcare_019", vertical: "healthcare", stakeholder: "Hospital administration", text: "Brief hospital administration on a near-miss that didn't reach a patient" },
    { id: "healthcare_020", vertical: "healthcare", stakeholder: "Nurse / care team", text: "Hand off a complex patient to the night shift who has limited context" },
    { id: "healthcare_021", vertical: "healthcare", stakeholder: "Insurance representative", text: "Push back on an insurer denying a procedure you believe is medically necessary" },
    { id: "healthcare_022", vertical: "healthcare", stakeholder: "Patient", text: "Explain a chronic diagnosis to a patient who's still hoping it'll go away" },
    { id: "healthcare_023", vertical: "healthcare", stakeholder: "Family member / caregiver", text: "Tell a family member it's time to think about end-of-life options" },
    { id: "healthcare_024", vertical: "healthcare", stakeholder: "Attending physician", text: "Disagree with an attending's diagnosis without sounding insubordinate" },
    { id: "healthcare_025", vertical: "healthcare", stakeholder: "Patient", text: "Tell a patient there's nothing more medicine can do" },
    { id: "healthcare_026", vertical: "healthcare", stakeholder: "Hospital administration", text: "Push back on staffing cuts that you believe will harm patient outcomes" },
    { id: "healthcare_027", vertical: "healthcare", stakeholder: "Patient", text: "Walk a patient through informed consent for a high-risk procedure" },
    { id: "healthcare_028", vertical: "healthcare", stakeholder: "Family member / caregiver", text: "Address a family member's anger that their loved one wasn't seen sooner" },
    { id: "healthcare_029", vertical: "healthcare", stakeholder: "Nurse / care team", text: "Coach a junior nurse who froze during a code" },
    { id: "healthcare_030", vertical: "healthcare", stakeholder: "Insurance representative", text: "Walk an insurance rep through why a step-therapy protocol failed" },
    { id: "healthcare_031", vertical: "healthcare", stakeholder: "Patient", text: "Explain why a medication is being changed to a patient who finally felt stable" },
    { id: "healthcare_032", vertical: "healthcare", stakeholder: "Attending physician", text: "Present a case where you suspect a colleague missed something" },
    { id: "healthcare_033", vertical: "healthcare", stakeholder: "Family member / caregiver", text: "Talk to a parent whose child was in the ICU overnight" },
    { id: "healthcare_034", vertical: "healthcare", stakeholder: "Patient", text: "Explain why a long-trusted doctor is no longer available" },
    { id: "healthcare_035", vertical: "healthcare", stakeholder: "Hospital administration", text: "Tell administration why your unit needs more beds, not fewer" },
    { id: "healthcare_036", vertical: "healthcare", stakeholder: "Nurse / care team", text: "Address a teammate whose documentation is creating downstream problems" },
    { id: "healthcare_037", vertical: "healthcare", stakeholder: "Patient", text: "Discuss a behavioral health referral with a resistant patient" },
    { id: "healthcare_038", vertical: "healthcare", stakeholder: "Family member / caregiver", text: "Tell a family the patient's wishes don't match what the family wants" },
    { id: "healthcare_039", vertical: "healthcare", stakeholder: "Attending physician", text: "Present a case where the right answer is to do nothing" },
    { id: "healthcare_040", vertical: "healthcare", stakeholder: "Insurance representative", text: "Walk an insurer through why a patient's case warrants an exception" },
    { id: "healthcare_041", vertical: "healthcare", stakeholder: "Patient", text: "Tell a long-term patient the practice is closing" },
    { id: "healthcare_042", vertical: "healthcare", stakeholder: "Hospital administration", text: "Recommend a clinical pathway change that will be unpopular with senior physicians" },
    { id: "healthcare_043", vertical: "healthcare", stakeholder: "Family member / caregiver", text: "Have a goals-of-care conversation with a family on day three of an ICU stay" },
    { id: "healthcare_044", vertical: "healthcare", stakeholder: "Patient", text: "Explain to a patient why their treatment timeline got slower" },
    { id: "healthcare_045", vertical: "healthcare", stakeholder: "Nurse / care team", text: "Brief the team on an outbreak protocol they'll be running starting tomorrow" },
    { id: "healthcare_046", vertical: "healthcare", stakeholder: "Attending physician", text: "Tell a senior attending you can't take any more admissions tonight" },
    { id: "healthcare_047", vertical: "healthcare", stakeholder: "Patient", text: "Explain why their genetic test results affect their family, not just them" },
    { id: "healthcare_048", vertical: "healthcare", stakeholder: "Hospital administration", text: "Defend a clinical decision under hospital administration scrutiny" },
    { id: "healthcare_049", vertical: "healthcare", stakeholder: "Insurance representative", text: "Field an insurance auditor's deep-dive on a complicated case" },
    { id: "healthcare_050", vertical: "healthcare", stakeholder: "Family member / caregiver", text: "Tell adult children that their parent should not be living alone anymore" },
  ],
  law: [
    { id: "law_001", vertical: "law", text: "Defend your legal argument to opposing counsel" },
    { id: "law_002", vertical: "law", text: "Explain a legal concept to a non-lawyer client" },
    { id: "law_003", vertical: "law", text: "Respond to a judge's pointed question about your position" },
    { id: "law_004", vertical: "law", text: "Present your client's position in opening remarks" },
    { id: "law_005", vertical: "law", text: "Break down a case to a jury" },
    { id: "law_006", vertical: "law", text: "Explain a precedent's relevance to the current matter" },
    { id: "law_007", vertical: "law", text: "Handle a cross-examination answer under pressure" },
    { id: "law_008", vertical: "law", text: "Counter an argument from opposing counsel" },
    { id: "law_009", vertical: "law", text: "Explain the risks of a decision to a client" },
    { id: "law_010", vertical: "law", text: "Walk a client through their options" },
    { id: "law_011", vertical: "law", text: "Explain why you're recommending settlement" },
    { id: "law_012", vertical: "law", text: "Respond to a client second-guessing your strategy" },
    { id: "law_013", vertical: "law", text: "Translate a statute into plain-language implications" },
    { id: "law_014", vertical: "law", text: "Explain a contract clause to a business stakeholder" },
    { id: "law_015", vertical: "law", text: "Deliver a verdict outcome to a client" },
    { id: "law_016", vertical: "law", stakeholder: "Client", text: "Tell a client they should accept a settlement they don't want to accept" },
    { id: "law_017", vertical: "law", stakeholder: "Opposing counsel", text: "Negotiate discovery scope with opposing counsel without giving up leverage" },
    { id: "law_018", vertical: "law", stakeholder: "Judge", text: "Argue a procedural motion in front of a judge known for impatience" },
    { id: "law_019", vertical: "law", stakeholder: "Jury", text: "Open a closing argument in a case where the facts are mostly against you" },
    { id: "law_020", vertical: "law", stakeholder: "Paralegal / associate", text: "Coach an associate whose memo you have to substantially rewrite" },
    { id: "law_021", vertical: "law", stakeholder: "Expert witness", text: "Prepare an expert witness for an aggressive cross-examination" },
    { id: "law_022", vertical: "law", stakeholder: "Client", text: "Tell a client they should plead guilty to avoid a worse outcome at trial" },
    { id: "law_023", vertical: "law", stakeholder: "Opposing counsel", text: "Make a settlement offer to opposing counsel without showing weakness" },
    { id: "law_024", vertical: "law", stakeholder: "Judge", text: "Walk a judge through a novel legal theory they're skeptical of" },
    { id: "law_025", vertical: "law", stakeholder: "Jury", text: "Defend a sympathetic plaintiff against your unsympathetic client to a jury" },
    { id: "law_026", vertical: "law", stakeholder: "Client", text: "Tell a client their case isn't strong enough to take to trial" },
    { id: "law_027", vertical: "law", stakeholder: "Paralegal / associate", text: "Tell an associate they're off the case for the second time this year" },
    { id: "law_028", vertical: "law", stakeholder: "Opposing counsel", text: "Push back on opposing counsel's deposition behavior without escalating" },
    { id: "law_029", vertical: "law", stakeholder: "Expert witness", text: "Walk an expert through how to handle a question they've never been asked" },
    { id: "law_030", vertical: "law", stakeholder: "Judge", text: "Apologize to a judge for a missed filing without sinking your credibility" },
    { id: "law_031", vertical: "law", stakeholder: "Client", text: "Tell a corporate client their CEO's emails will be produced in discovery" },
    { id: "law_032", vertical: "law", stakeholder: "Jury", text: "Cross-examine a sympathetic witness without alienating the jury" },
    { id: "law_033", vertical: "law", stakeholder: "Opposing counsel", text: "Tell opposing counsel you're filing for sanctions without sounding hostile" },
    { id: "law_034", vertical: "law", stakeholder: "Client", text: "Walk a client through the trial outcome they wanted but didn't fully win" },
    { id: "law_035", vertical: "law", stakeholder: "Paralegal / associate", text: "Brief a junior on a sensitive matter they need to keep confidential" },
    { id: "law_036", vertical: "law", stakeholder: "Judge", text: "Argue an objection in real time during a heated exchange" },
    { id: "law_037", vertical: "law", stakeholder: "Expert witness", text: "Reassure an expert who just got rattled on the stand at break" },
    { id: "law_038", vertical: "law", stakeholder: "Client", text: "Walk a corporate client through what a regulatory subpoena means for their business" },
    { id: "law_039", vertical: "law", stakeholder: "Jury", text: "Re-engage a jury that's been losing focus on day three of trial" },
    { id: "law_040", vertical: "law", stakeholder: "Opposing counsel", text: "Take a hard-line position with opposing counsel without burning the relationship for the next case" },
    { id: "law_041", vertical: "law", stakeholder: "Client", text: "Tell a client your firm has a conflict and can't represent them in this matter" },
    { id: "law_042", vertical: "law", stakeholder: "Judge", text: "Defend a controversial legal position to a judge who openly disagrees" },
    { id: "law_043", vertical: "law", stakeholder: "Paralegal / associate", text: "Walk an associate through why a memo they thought was done isn't done" },
    { id: "law_044", vertical: "law", stakeholder: "Expert witness", text: "Tell an expert their preferred testimony won't fly under the current rules" },
    { id: "law_045", vertical: "law", stakeholder: "Client", text: "Tell a client a regulator is requesting documents about them by name" },
    { id: "law_046", vertical: "law", stakeholder: "Jury", text: "Address a jury when your own witness contradicted themselves" },
    { id: "law_047", vertical: "law", stakeholder: "Opposing counsel", text: "Walk through a stipulation negotiation where neither side can be seen losing" },
    { id: "law_048", vertical: "law", stakeholder: "Client", text: "Tell a client their internal investigation has uncovered something they need to disclose" },
    { id: "law_049", vertical: "law", stakeholder: "Paralegal / associate", text: "Brief an associate on a partner whose feedback they should weigh more heavily than yours" },
    { id: "law_050", vertical: "law", stakeholder: "Judge", text: "Apologize for a colleague's misconduct that the judge is about to address from the bench" },
  ],
  education: [
    { id: "education_001", vertical: "education", text: "Teach a concept to a student who's struggling" },
    { id: "education_002", vertical: "education", text: "Simplify a complex idea for different learning levels" },
    { id: "education_003", vertical: "education", text: "Guide a student through a problem without giving the answer" },
    { id: "education_004", vertical: "education", text: "Explain a concept step-by-step" },
    { id: "education_005", vertical: "education", text: "Help someone understand a topic they're intimidated by" },
    { id: "education_006", vertical: "education", text: "Give a student feedback on work that isn't quite there" },
    { id: "education_007", vertical: "education", text: "Explain why a subject matters outside the classroom" },
    { id: "education_008", vertical: "education", text: "Respond to 'when will I ever use this in real life?'" },
    { id: "education_009", vertical: "education", text: "Walk a parent through their child's progress" },
    { id: "education_010", vertical: "education", text: "Introduce a new topic to get students curious" },
    { id: "education_011", vertical: "education", text: "Handle a student who disagrees with you in class" },
    { id: "education_012", vertical: "education", text: "Explain a historical event to make it feel present" },
    { id: "education_013", vertical: "education", text: "Teach a concept to a mixed-ability classroom" },
    { id: "education_014", vertical: "education", text: "Respond to a student's genuine confusion with patience" },
    { id: "education_015", vertical: "education", text: "Explain a correction without discouraging the student" },
    { id: "education_016", vertical: "education", stakeholder: "Student", text: "Talk to a student who's been quiet all semester after a tough family change" },
    { id: "education_017", vertical: "education", stakeholder: "Parent / guardian", text: "Explain to a parent why their child needs additional support" },
    { id: "education_018", vertical: "education", stakeholder: "Department chair", text: "Pitch a curriculum change to your department chair" },
    { id: "education_019", vertical: "education", stakeholder: "Principal / dean", text: "Push back on the principal's request to cut your department's budget" },
    { id: "education_020", vertical: "education", stakeholder: "Colleague teacher", text: "Coach a colleague whose classroom management is slipping" },
    { id: "education_021", vertical: "education", stakeholder: "School board", text: "Defend a controversial reading list to a school board" },
    { id: "education_022", vertical: "education", stakeholder: "Student", text: "Tell a student their work isn't good enough — and they have time to fix it" },
    { id: "education_023", vertical: "education", stakeholder: "Parent / guardian", text: "Tell a parent their child cheated on a major assignment" },
    { id: "education_024", vertical: "education", stakeholder: "Department chair", text: "Push back on a chair who keeps adding admin duties to your role" },
    { id: "education_025", vertical: "education", stakeholder: "Principal / dean", text: "Tell the principal you can't add another duty without something else dropping" },
    { id: "education_026", vertical: "education", stakeholder: "Student", text: "Help a student who's lost confidence after a string of bad grades" },
    { id: "education_027", vertical: "education", stakeholder: "Parent / guardian", text: "Tell a parent that pushing harder is making things worse" },
    { id: "education_028", vertical: "education", stakeholder: "Colleague teacher", text: "Confront a colleague whose behavior in the staff lounge is inappropriate" },
    { id: "education_029", vertical: "education", stakeholder: "School board", text: "Brief a school board on a discipline incident before they hear it from someone else" },
    { id: "education_030", vertical: "education", stakeholder: "Student", text: "Walk a student through why their idea was good but the execution wasn't" },
    { id: "education_031", vertical: "education", stakeholder: "Parent / guardian", text: "Talk to a parent who keeps emailing about minor issues" },
    { id: "education_032", vertical: "education", stakeholder: "Department chair", text: "Recommend an unconventional teaching approach to your chair" },
    { id: "education_033", vertical: "education", stakeholder: "Principal / dean", text: "Push back on the principal placing a difficult student in your already-loaded class" },
    { id: "education_034", vertical: "education", stakeholder: "Student", text: "Address a student who's been disrespectful in class without escalating it" },
    { id: "education_035", vertical: "education", stakeholder: "Colleague teacher", text: "Mentor a first-year teacher who's overwhelmed in October" },
    { id: "education_036", vertical: "education", stakeholder: "Parent / guardian", text: "Defend a grade you gave to a parent who's threatening to escalate" },
    { id: "education_037", vertical: "education", stakeholder: "Student", text: "Explain to a senior why their college essay is missing the point" },
    { id: "education_038", vertical: "education", stakeholder: "School board", text: "Make the case to a school board that mental health support is non-negotiable" },
    { id: "education_039", vertical: "education", stakeholder: "Principal / dean", text: "Tell the dean that your team can't sustain the schedule they proposed" },
    { id: "education_040", vertical: "education", stakeholder: "Department chair", text: "Recommend ending a long-running tradition that's no longer effective" },
    { id: "education_041", vertical: "education", stakeholder: "Student", text: "Talk to a high-performer who's plateaued and stopped trying" },
    { id: "education_042", vertical: "education", stakeholder: "Parent / guardian", text: "Walk a parent through their child's IEP results without softening the truth" },
    { id: "education_043", vertical: "education", stakeholder: "Colleague teacher", text: "Tell a colleague their grading is out of step with the rest of the team" },
    { id: "education_044", vertical: "education", stakeholder: "Student", text: "Discuss a personal disclosure a student made in their journal" },
    { id: "education_045", vertical: "education", stakeholder: "School board", text: "Defend a hiring decision that the school board questioned" },
    { id: "education_046", vertical: "education", stakeholder: "Principal / dean", text: "Tell the principal you're considering leaving the school" },
    { id: "education_047", vertical: "education", stakeholder: "Department chair", text: "Walk a chair through why your subject deserves more class time" },
    { id: "education_048", vertical: "education", stakeholder: "Student", text: "Re-engage a student who's been staring at their phone all week" },
    { id: "education_049", vertical: "education", stakeholder: "Parent / guardian", text: "Tell a parent the child you've all worked on is repeating the year" },
    { id: "education_050", vertical: "education", stakeholder: "Colleague teacher", text: "Address a colleague who keeps undermining you in front of students" },
  ],
  leadership: [
    { id: "leadership_001", vertical: "leadership", text: "Give a direct report feedback on their performance" },
    { id: "leadership_002", vertical: "leadership", text: "Address a team member whose work is slipping" },
    { id: "leadership_003", vertical: "leadership", text: "Align the team around a new priority" },
    { id: "leadership_004", vertical: "leadership", text: "Handle a conflict between two direct reports" },
    { id: "leadership_005", vertical: "leadership", text: "Communicate an unpopular decision to the team" },
    { id: "leadership_006", vertical: "leadership", text: "Explain a change that people won't like" },
    { id: "leadership_007", vertical: "leadership", text: "Praise someone publicly in a way that lands" },
    { id: "leadership_008", vertical: "leadership", text: "Coach a report through a mistake without lecturing" },
    { id: "leadership_009", vertical: "leadership", text: "Deliver news that a project is being cancelled" },
    { id: "leadership_010", vertical: "leadership", text: "Tell a high performer they won't get promoted this cycle" },
    { id: "leadership_011", vertical: "leadership", text: "Defend a team member to a skeptical VP" },
    { id: "leadership_012", vertical: "leadership", text: "Explain why you're reorganizing the team" },
    { id: "leadership_013", vertical: "leadership", text: "Handle a report who disagrees with a decision you made" },
    { id: "leadership_014", vertical: "leadership", text: "Give feedback to your own manager" },
    { id: "leadership_015", vertical: "leadership", text: "Announce a layoff to a team you care about" },
    { id: "leadership_016", vertical: "leadership", stakeholder: "Direct report", text: "Tell a direct report you don't think they're going to make it in this role" },
    { id: "leadership_017", vertical: "leadership", stakeholder: "Skip-level report", text: "Run a skip-level meeting where the team has lost trust in their manager" },
    { id: "leadership_018", vertical: "leadership", stakeholder: "Peer leader", text: "Tell a peer leader their team is blocking yours and it has to stop" },
    { id: "leadership_019", vertical: "leadership", stakeholder: "Executive team", text: "Push back on the executive team's strategy without sounding insubordinate" },
    { id: "leadership_020", vertical: "leadership", stakeholder: "Board / investor", text: "Tell the board you're behind plan and you have a real reason, not an excuse" },
    { id: "leadership_021", vertical: "leadership", stakeholder: "All-hands / town hall", text: "Open an all-hands the day after a difficult news cycle" },
    { id: "leadership_022", vertical: "leadership", stakeholder: "External partner", text: "Tell an external partner the relationship is being downgraded" },
    { id: "leadership_023", vertical: "leadership", stakeholder: "Direct report", text: "Praise a direct report in a way that motivates without inflating them" },
    { id: "leadership_024", vertical: "leadership", stakeholder: "Cross-functional partner", text: "Push back on a peer team's request that would derail your roadmap" },
    { id: "leadership_025", vertical: "leadership", stakeholder: "Executive team", text: "Recommend pausing a strategic initiative the CEO championed" },
    { id: "leadership_026", vertical: "leadership", stakeholder: "Board / investor", text: "Brief the board on a regulatory issue they don't yet know about" },
    { id: "leadership_027", vertical: "leadership", stakeholder: "Direct report", text: "Tell a high-performer they're not getting the promotion this cycle" },
    { id: "leadership_028", vertical: "leadership", stakeholder: "Skip-level report", text: "Coach a skip-level on how to push back on their manager" },
    { id: "leadership_029", vertical: "leadership", stakeholder: "All-hands / town hall", text: "Address a town hall after a controversial product decision goes public" },
    { id: "leadership_030", vertical: "leadership", stakeholder: "Peer leader", text: "Have the conversation with a peer leader about who's actually responsible for a missed result" },
    { id: "leadership_031", vertical: "leadership", stakeholder: "Direct report", text: "Tell a long-tenured employee their role is being changed" },
    { id: "leadership_032", vertical: "leadership", stakeholder: "Executive team", text: "Recommend cutting an expensive project the executive team funded" },
    { id: "leadership_033", vertical: "leadership", stakeholder: "Board / investor", text: "Tell investors you've changed your mind about a strategic direction you sold them on" },
    { id: "leadership_034", vertical: "leadership", stakeholder: "Direct report", text: "Coach a manager-level report whose team is complaining about their style" },
    { id: "leadership_035", vertical: "leadership", stakeholder: "All-hands / town hall", text: "Open a town hall after a beloved leader resigns" },
    { id: "leadership_036", vertical: "leadership", stakeholder: "Peer leader", text: "Tell a peer leader their direct report is making your team's life harder" },
    { id: "leadership_037", vertical: "leadership", stakeholder: "External partner", text: "Renegotiate terms with an external partner who has more leverage than you" },
    { id: "leadership_038", vertical: "leadership", stakeholder: "Direct report", text: "Address a direct report whose performance has suddenly dropped" },
    { id: "leadership_039", vertical: "leadership", stakeholder: "Executive team", text: "Walk the executive team through your team's biggest single point of failure" },
    { id: "leadership_040", vertical: "leadership", stakeholder: "Skip-level report", text: "Tell a skip-level you don't agree with their manager's plan, without undermining the manager" },
    { id: "leadership_041", vertical: "leadership", stakeholder: "Direct report", text: "Tell a direct report they're being put on a performance plan" },
    { id: "leadership_042", vertical: "leadership", stakeholder: "Board / investor", text: "Defend a strategy pivot the board didn't expect and isn't sure about" },
    { id: "leadership_043", vertical: "leadership", stakeholder: "All-hands / town hall", text: "Address a layoff in a town hall — without notes" },
    { id: "leadership_044", vertical: "leadership", stakeholder: "Peer leader", text: "Tell a peer leader you're going to take credit for a project they think is theirs" },
    { id: "leadership_045", vertical: "leadership", stakeholder: "Direct report", text: "Mentor a junior leader who's been overpromising to their team" },
    { id: "leadership_046", vertical: "leadership", stakeholder: "Cross-functional partner", text: "Push back on a peer team's metric that's hurting your team's incentives" },
    { id: "leadership_047", vertical: "leadership", stakeholder: "Executive team", text: "Tell the executive team a key engineer just resigned and you don't have a plan yet" },
    { id: "leadership_048", vertical: "leadership", stakeholder: "Direct report", text: "Tell a direct report you're going to rehire the role they thought they were getting" },
    { id: "leadership_049", vertical: "leadership", stakeholder: "All-hands / town hall", text: "Address the team after rumors of a sale start spreading" },
    { id: "leadership_050", vertical: "leadership", stakeholder: "External partner", text: "End a relationship with a long-time vendor without poisoning the goodwill" },
  ],
  other: [
    { id: "other_001", vertical: "other", text: "Explain why a habit matters to you" },
    { id: "other_002", vertical: "other", text: "Give a short talk on something you've learned recently" },
    { id: "other_003", vertical: "other", text: "Make a case for something you believe in" },
    { id: "other_004", vertical: "other", text: "Teach someone a skill you know well" },
    { id: "other_005", vertical: "other", text: "Respond to a question you weren't prepared for" },
    { id: "other_006", vertical: "other", text: "Describe a problem you're currently working through" },
    { id: "other_007", vertical: "other", text: "Explain a decision you're about to make" },
    { id: "other_008", vertical: "other", text: "Share a lesson from a failure" },
    { id: "other_009", vertical: "other", text: "Defend an opinion you hold" },
    { id: "other_010", vertical: "other", text: "Describe a challenge you're facing and your approach" },
    { id: "other_011", vertical: "other", text: "Make a recommendation to a friend" },
    { id: "other_012", vertical: "other", text: "Explain something you find fascinating" },
    { id: "other_013", vertical: "other", text: "Walk through your reasoning for a recent choice" },
    { id: "other_014", vertical: "other", text: "Respond to honest feedback you disagree with" },
    { id: "other_015", vertical: "other", text: "Tell a story with a clear point" },
    { id: "other_016", vertical: "other", stakeholder: "Colleague", text: "Tell a colleague their proposal needs more thought before going to leadership" },
    { id: "other_017", vertical: "other", stakeholder: "Manager", text: "Ask your manager for time to focus on a project they didn't prioritize" },
    { id: "other_018", vertical: "other", stakeholder: "Client", text: "Tell a client their project is going to take longer than promised" },
    { id: "other_019", vertical: "other", stakeholder: "Audience / room", text: "Open a presentation when you've never spoken to this kind of audience before" },
    { id: "other_020", vertical: "other", stakeholder: "Stranger", text: "Explain what you do for work to a stranger who's never heard of your industry" },
    { id: "other_021", vertical: "other", stakeholder: "Friend or family", text: "Tell a family member you can't make it to a major event" },
    { id: "other_022", vertical: "other", stakeholder: "Colleague", text: "Push back on a colleague's idea that won't work in your context" },
    { id: "other_023", vertical: "other", stakeholder: "Manager", text: "Have a real conversation with your manager about your career direction" },
    { id: "other_024", vertical: "other", stakeholder: "Client", text: "Tell a client you're going to charge more on the next phase" },
    { id: "other_025", vertical: "other", stakeholder: "Audience / room", text: "Open a panel when nobody in the room has heard of you" },
    { id: "other_026", vertical: "other", stakeholder: "Stranger", text: "Make small talk with a stranger sitting next to you on a long flight" },
    { id: "other_027", vertical: "other", stakeholder: "Friend or family", text: "Tell a friend their plans are making you uncomfortable" },
    { id: "other_028", vertical: "other", stakeholder: "Colleague", text: "Onboard a colleague joining your project mid-stream" },
    { id: "other_029", vertical: "other", stakeholder: "Manager", text: "Tell your manager about a workload issue without sounding like complaining" },
    { id: "other_030", vertical: "other", stakeholder: "Client", text: "Open a kickoff with a client whose previous vendor relationship ended badly" },
    { id: "other_031", vertical: "other", stakeholder: "Audience / room", text: "Speak to an audience that's mostly here for the next presenter" },
    { id: "other_032", vertical: "other", stakeholder: "Stranger", text: "Strike up conversation with someone at an event where you know no one" },
    { id: "other_033", vertical: "other", stakeholder: "Friend or family", text: "Tell a friend you can't loan them money this time" },
    { id: "other_034", vertical: "other", stakeholder: "Colleague", text: "Coach a colleague who keeps falling behind without making it about competence" },
    { id: "other_035", vertical: "other", stakeholder: "Manager", text: "Pitch your manager on changing how 1:1s work" },
    { id: "other_036", vertical: "other", stakeholder: "Client", text: "Walk a client through a deliverable that came back below your usual quality" },
    { id: "other_037", vertical: "other", stakeholder: "Audience / room", text: "Address a room that's been waiting longer than expected because of tech issues" },
    { id: "other_038", vertical: "other", stakeholder: "Stranger", text: "Explain a complex personal interest to someone who's politely asking" },
    { id: "other_039", vertical: "other", stakeholder: "Friend or family", text: "Tell a parent something they don't want to hear about your future plans" },
    { id: "other_040", vertical: "other", stakeholder: "Hiring manager / interviewer", text: "Open an interview when you're already running late" },
    { id: "other_041", vertical: "other", stakeholder: "Colleague", text: "Hand off a project to a colleague who didn't want it" },
    { id: "other_042", vertical: "other", stakeholder: "Manager", text: "Have the conversation with your manager about flexible hours" },
    { id: "other_043", vertical: "other", stakeholder: "Client", text: "Tell a long-time client you're moving on to a new firm" },
    { id: "other_044", vertical: "other", stakeholder: "Audience / room", text: "Speak to a room of skeptics about a topic that's polarized in your field" },
    { id: "other_045", vertical: "other", stakeholder: "Hiring manager / interviewer", text: "Answer 'why are you leaving your current job?' honestly without trash-talking" },
    { id: "other_046", vertical: "other", stakeholder: "Friend or family", text: "Apologize to a sibling for something that happened years ago" },
    { id: "other_047", vertical: "other", stakeholder: "Colleague", text: "Tell a colleague their feedback wasn't useful but you appreciate them giving it" },
    { id: "other_048", vertical: "other", stakeholder: "Manager", text: "Explain a recurring mistake you keep making and what you're doing about it" },
    { id: "other_049", vertical: "other", stakeholder: "Client", text: "Walk a new client through your process so they know what to expect" },
    { id: "other_050", vertical: "other", stakeholder: "Audience / room", text: "Speak at a memorial in a way that's honest, brief, and warm" },
  ],
};

/** O(1) id → prompt lookup, built once at module load. */
const VERTICAL_PROMPT_INDEX: ReadonlyMap<string, VerticalPrompt> = (() => {
  const map = new Map<string, VerticalPrompt>();
  for (const bank of Object.values(VERTICAL_PROMPTS)) {
    for (const p of bank) map.set(p.id, p);
  }
  return map;
})();

/** Look up a single vertical prompt object by id. */
export function getVerticalPromptById(id: string): VerticalPrompt | undefined {
  return VERTICAL_PROMPT_INDEX.get(id);
}

function shuffleAndTake(
  bank: readonly VerticalPrompt[],
  count: number,
  rand: () => number,
): VerticalPrompt[] {
  const shuffled = [...bank];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j]!, shuffled[i]!];
  }
  return shuffled.slice(0, Math.min(count, shuffled.length));
}

/**
 * Pick N prompt objects from a vertical's bank. Vertical banks are
 * single-vertical by definition, so there's no theme stratification —
 * the whole bank is the user's vertical. Stakeholder-based stratification
 * activates once expansion-pass prompts populate the optional
 * `stakeholder` field.
 *
 * `excludeIds` filters out prompts the user has already seen across
 * sessions. Falls back to the seen pool when filtering empties the bank.
 */
export function pickVerticalPromptObjects(
  vertical: VerticalId,
  count: number = 5,
  opts: { rand?: () => number; excludeIds?: ReadonlySet<string> } = {},
): VerticalPrompt[] {
  const bank = VERTICAL_PROMPTS[vertical];
  if (!bank || bank.length === 0) return [];
  const rand = opts.rand ?? Math.random;
  const exclude = opts.excludeIds;

  if (!exclude || exclude.size === 0) {
    return shuffleAndTake(bank, count, rand);
  }

  const unseen = bank.filter((p) => !exclude.has(p.id));
  const pool = unseen.length > 0 ? unseen : bank;
  const picks = shuffleAndTake(pool, count, rand);

  if (picks.length < count && pool === unseen && unseen.length < bank.length) {
    const seen = bank.filter((p) => exclude.has(p.id));
    const extras = shuffleAndTake(seen, count - picks.length, rand);
    return [...picks, ...extras];
  }
  return picks;
}

/** Text-returning picker — thin wrapper for callers that don't need ids. */
export function pickVerticalPrompts(
  vertical: VerticalId,
  count: number = 5,
  opts: { rand?: () => number; excludeIds?: ReadonlySet<string> } = {},
): string[] {
  return pickVerticalPromptObjects(vertical, count, opts).map((p) => p.text);
}

/** Total number of prompts available in a vertical's bank. */
export function verticalBankSize(vertical: VerticalId): number {
  return VERTICAL_PROMPTS[vertical]?.length ?? 0;
}
