-- 0006_dna_v3_dimension_tone.sql
-- DNA reconciliation (2026-05-01) — Adaptability is renamed to Tone in
-- the v3 rubric. Postgres cannot remove enum values with existing rows
-- referencing them, so the migration is purely additive: ensure 'tone'
-- exists in the dimension enum.
--
-- The 'tone' value already existed in the enum from v1 (see migration
-- 0001) and was repurposed there as a legacy name for adaptability via
-- src/lib/scoring/dimension-aliases.ts. As of v3, 'tone' is once again
-- the canonical name; 'adaptability' is now the legacy alias.
-- This migration is therefore a no-op against any existing dev/prod
-- database — IF NOT EXISTS guards keep it idempotent.
--
-- Application-level code (src/lib/scoring/dimension-aliases.ts) handles
-- the read-time projection: rows with dimension='adaptability' now
-- surface as 'tone' to the UI, and v1 'tone' rows continue to surface
-- as 'tone' (now matching the canonical name directly).
--
-- IRREVERSIBLE for data semantics — once v3 reps land with
-- dimension='tone', rolling back means treating those rows as v1-style
-- tone (different signal definition). Code rollback retains data
-- integrity; rubric semantics are forward-only.

ALTER TYPE "cognify_v2"."dimension" ADD VALUE IF NOT EXISTS 'tone';
