import { serve } from "https://deno.land/std@0.192.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

serve(async (req) => {
  // ✅ Handle CORS preflight
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    if (req.method !== "POST") {
      return new Response(
        JSON.stringify({ error: "Method not allowed" }),
        {
          status: 405,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    // ✅ Parse multipart form data
    const formData = await req.formData();

    const audioFile = formData.get("audio") as File | null;
    const framework = formData.get("framework")?.toString() ?? "";
    const audience = formData.get("audience")?.toString() ?? "";
    const scenario = formData.get("scenario")?.toString() ?? "";
    const preRepIntent = formData.get("preRepIntent")?.toString() ?? "";

    if (!audioFile) {
      return new Response(
        JSON.stringify({ error: "No audio file provided" }),
        {
          status: 400,
          headers: { ...corsHeaders, "Content-Type": "application/json" },
        }
      );
    }

    // ✅ Read audio bytes (ready for real transcription later)
    const audioBuffer = await audioFile.arrayBuffer();

    console.log("Received audio bytes:", audioBuffer.byteLength);
    console.log("Framework:", framework);
    console.log("Audience:", audience);

    // -------------------------------------------------------
    // 🔥 TEMP MOCK RESPONSE (Replace with real AI later)
    // -------------------------------------------------------

    const transcript =
      "This is a mock transcript generated by the analyze-rep Edge function.";

    const analysis = {
      clarity: 82,
      structure: 75,
      brevity: 68,
      confidence: 88,
      pacing: 70,
      presence: 85,
      fillerWordCount: 6,
      overallScore: 79,
    };

    const feedback = {
      strengths: [
        "Strong confident tone",
        "Clear structure throughout",
      ],
      improvements: [
        "Reduce filler words",
        "Tighten key points",
      ],
      nextFocus: {
        title: "Improve Brevity",
        nextStep:
          "Practice delivering your core point in under 30 seconds.",
      },
      summary:
        "Overall strong delivery. Focus on tightening your messaging and reducing filler words.",
    };

    // -------------------------------------------------------

    return new Response(
      JSON.stringify({
        transcript,
        analysis,
        feedback,
      }),
      {
        status: 200,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      }
    );
  } catch (error) {
    console.error("Edge function error:", error);

    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      {
        status: 500,
        headers: {
          ...corsHeaders,
          "Content-Type": "application/json",
        },
      }
    );
  }
});