import { useState, useEffect } from "react";
import { useNavigate, useOutletContext } from "react-router-dom";
import { RepSetup } from "./pages/RepSetup";
import { RepPerform } from "./pages/RepPerform";
import { TextFeedbackScreen } from "./components/tryitout/TextFeedbackScreen";
import { ProcessingScreen } from "./components/tryitout/ProcessingScreen";
import { RepHistoryPage } from "./components/tryitout/RepHistoryPage";
import { Rep } from "./types/rep";
import { useAuth } from "../context/AuthContext";
import { useReps } from "../context/RepsContext";
import { supabase } from "../lib/supabase";

type ViewState = "setup" | "perform" | "processing" | "feedback" | "history";

export default function TryItOut() {
  const navigate = useNavigate();
  const { session } = useAuth();
  const { repHistory, refetchReps } = useReps();
  const [viewState, setViewState] = useState<ViewState>("setup");
  const [repConfig, setRepConfig] = useState<{
    vertical: string;
    scenario: string;
    audience: string;
    framework: string;
    timeLimit: number;
  } | null>(null);
  const [currentRepData, setCurrentRepData] = useState<{
    preRepIntent: string;
    frameworkInputs: Record<string, string>;
    audioBlob: Blob;
    transcript: string;
    duration: number;
  } | null>(null);
  const [repsCompleted, setRepsCompleted] = useState(0);
  const [currentClarityScore, setCurrentClarityScore] = useState(0);
  const [currentPrimaryFocus, setCurrentPrimaryFocus] = useState<{ title: string; nextStep: string } | null>(null);
  const [isRecording, setIsRecording] = useState(false);
  const outletContext = useOutletContext<{ setDisableNavigation?: (v: boolean) => void }>();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [viewState]);

  const handleRecordingStateChange = (recording: boolean) => {
    setIsRecording(recording);
    outletContext?.setDisableNavigation?.(recording);
  };

  useEffect(() => {
    return () => {
      outletContext?.setDisableNavigation?.(false);
    };
  }, [outletContext?.setDisableNavigation]);

  const handleSetupContinue = (config: {
    vertical: string;
    scenario: string;
    audience: string;
    framework: string;
    timeLimit: number;
  }) => {
    setRepConfig(config);
    setViewState("perform");
  };

  const handleSetupBack = () => {
    setViewState("setup");
    setRepConfig(null);
  };

  const handlePerformSubmit = (data: {
    preRepIntent: string;
    frameworkInputs: Record<string, string>;
    audioBlob: Blob;
    transcript: string;
    duration: number;
  }) => {
    setCurrentRepData(data);
    setViewState("processing");

    // Simulate processing
    setTimeout(() => {
      setViewState("feedback");
    }, 1500);
  };

  const handlePerformBack = () => {
    setViewState("setup");
  };

  const handleFeedbackGenerated = async (
    score: number,
    focus: { title: string; nextStep: string },
    detailedScores?: { clarity?: number; structure?: number; brevity?: number; confidence?: number },
    _analysisMetrics?: unknown
  ) => {
    setCurrentClarityScore(score);
    setCurrentPrimaryFocus(focus);
    setRepsCompleted((prev) => prev + 1);
  
    if (!repConfig || !currentRepData || !session?.user?.id) return;
  
    try {
      // 1️⃣ Upload audio
      const storagePath = `${session.user.id}/${Date.now()}.webm`;
  
      const { error: uploadError } = await supabase.storage
        .from("rep-audio")
        .upload(storagePath, currentRepData.audioBlob, {
          contentType: "audio/webm",
        });
  
      if (uploadError) {
        console.error("Upload error:", uploadError);
        return;
      }
  
      const { data: signed } = await supabase.storage
        .from("rep-audio")
        .createSignedUrl(storagePath, 3600);
  
      const audioUrl = signed?.signedUrl ?? null;
  
      // 2️⃣ Insert rep with pending status
      const { data: insertedRep, error: repsError } = await supabase
        .from("reps")
        .insert({
          user_id: session.user.id,
          transcript: "", // transcript will be generated by Edge Function
          transcript_word_count: 0,
          overall_score: null,
          delivery_score: null,
          content_score: null,
          audio_url: audioUrl,
          status: "pending",
        })
        .select("id")
        .single();
  
      if (repsError || !insertedRep?.id) {
        console.error("Rep insert error:", repsError);
        return;
      }
  
      // 3️⃣ Insert placeholder delivery row
      await supabase.from("delivery_scores").insert({
        rep_id: insertedRep.id,
        pace: 0,
        clarity: 0,
        filler_words: 0,
        confidence: 0,
        pauses: 0,
        tone: 0,
        overall_delivery: 0,
      });
  
      const { data: functionData, error: functionError } =
      await supabase.functions.invoke("score-rep", {
        body: { repId: insertedRep.id },
      });
    
    if (functionError) {
      console.error("Edge function error:", functionError);
      return;
    }
  
      // 5️⃣ Refetch reps after scoring completes
      await refetchReps();
  
    } catch (err) {
      console.error("Unexpected error:", err);
    }
  };
  

  const handleNextRep = () => {
    setViewState("setup");
    setRepConfig(null);
    setCurrentRepData(null);
  };

  const handleViewHistory = () => {
    setViewState("history");
  };

  const handleBackToFeedback = () => {
    setViewState("feedback");
  };

  const handleSelectHistoryRep = (rep: Rep) => {
    // Could show detailed view of historical rep
    console.log("Selected rep:", rep);
  };

  return (
    <div className="min-h-screen bg-white flex flex-col">
      {viewState === "setup" && (
        <RepSetup
          onContinue={handleSetupContinue}
          onBack={() => { navigate("/"); window.scrollTo(0, 0); }}
        />
      )}

      {viewState === "perform" && repConfig && (
        <RepPerform
          config={repConfig}
          onSubmit={handlePerformSubmit}
          onBack={handlePerformBack}
          onRecordingStateChange={handleRecordingStateChange}
        />
      )}

      {viewState === "processing" && (
        <ProcessingScreen />
      )}

      {viewState === "feedback" && repConfig && currentRepData && (
        <TextFeedbackScreen
          scenario={repConfig.scenario}
          audience={repConfig.audience}
          framework={repConfig.framework}
          preRepIntent={currentRepData.preRepIntent}
          transcript={currentRepData.transcript}
          repNumber={repsCompleted + 1}
          onFeedbackGenerated={handleFeedbackGenerated}
          onNextRep={handleNextRep}
          onViewHistory={handleViewHistory}
        />
      )}

      {viewState === "history" && (
        <RepHistoryPage
          reps={repHistory}
          onBack={handleBackToFeedback}
          onSelectRep={handleSelectHistoryRep}
        />
      )}
    </div>
  );
}
