// Sales recalibration Wave 4 - HALF 1 (first 27 exercises sorted by dimension+name)
// Authors 27 exercises x 10 goals x 3 archetypes = 810 prompts.
// Appends to scripts/exercise-catalog/v1/vertical/sales.json.
//
// Authoring rules per docs/prompt-design-canon.md:
//   - Repeatable on demand: no required setup, user speaks in 3 seconds
//   - Mechanic-aligned: each exercise's move is path of least resistance
//   - Vertical-flavored: sales themes (deals, buyers, pitches, discovery)
//                       not vertical-locked scenes (no specific CFO/procurement scenes)
//   - NO mechanic prefixes in text ("Lead with the headline:" etc are BANNED)
//   - NO specific-scene scenarios ("your CFO asking for 40% discount...")
//   - ≤180 chars, conversational, second-person.
// Difficulty mix target: ~50% intro / ~40% core / ~10% stretch.
// Target user: AE 1-3 yrs, SDR/BDR, CSM (NOT sales VPs).

import fs from "node:fs";

const CATALOG_PATH = "C:/Users/MaxVolkov/dev/cognify/scripts/exercise-catalog/v1/vertical/sales.json";

const GOALS = [
  "handling_objections",
  "confidence",
  "thinking_on_the_spot",
  "giving_feedback",
  "negotiation",
  "presenting",
  "persuasion",
  "storytelling",
  "asking_questions",
  "explaining",
];

// Difficulty plan: roughly 50/40/10.
const D = { intro: "intro", core: "core", stretch: "stretch" };
const archDiff = (arch, exIdx, goalIdx) => {
  const i = exIdx * 10 + goalIdx;
  if (arch === "A") {
    // mostly intro
    return i % 7 === 0 ? D.core : D.intro;
  }
  if (arch === "B") {
    // mostly core, occasional stretch and intro
    const m = i % 10;
    if (m === 0) return D.stretch;
    if (m <= 2) return D.intro;
    return D.core;
  }
  // C: mix with more stretch
  const m = i % 10;
  if (m <= 1) return D.intro;
  if (m >= 8) return D.stretch;
  return D.core;
};

// ============================================================================
// UNIVERSAL CRAFT POOL (archetype A) — 30+ per goal.
// Anyone could speak to these regardless of vertical. They pull each mechanic
// by their shape (yes/no for headline, opinion for steel-man, etc).
// We pick by (exerciseIdx, goalIdx) using diagonal indexing for variety.
// ============================================================================

const A_BY_GOAL = {
  handling_objections: [
    "What's the truest thing about why people push back hard?",
    "Why does winning the argument sometimes lose the room?",
    "What changes someone's mind faster — proof or pause?",
    "When someone disagrees, where do you actually start?",
    "What does pushback usually really mean?",
    "Is the loudest objection the real one?",
    "What's the move when someone won't budge?",
    "When is 'no' actually 'not yet'?",
    "What do you do when you're caught flat-footed by pushback?",
    "Why do most rebuttals sound like arguments?",
    "What separates a clean comeback from a defensive one?",
    "When should you concede a point to win the bigger one?",
    "What's the question that diffuses pushback fastest?",
    "Why does empathy land better than logic under fire?",
    "What's the worst way to answer a hard objection?",
    "How do you stay steady when someone gets aggressive?",
    "When is silence the right answer to an objection?",
    "What's the cleanest way to disagree without escalating?",
    "Why do hedged answers invite more pushback?",
    "What do you do when the objection is half right?",
    "When does explaining make resistance worse?",
    "What's the difference between a real objection and a smokescreen?",
    "How do you tell the difference between curiosity and pushback?",
    "What's something you'd say less of, on a pushback?",
    "When did pushback actually save you from a mistake?",
    "What's a question that sounds soft but cuts deep?",
    "Why does over-answering kill credibility?",
    "When should you just say 'fair point'?",
    "What's the right pace to answer something heated?",
    "Why is the second answer usually better than the first?",
    "When is the right time to stop defending?",
    "What's the move when both sides feel right?",
  ],
  confidence: [
    "What does real confidence actually sound like?",
    "Where does your confidence come from on a tough day?",
    "Is quiet confidence stronger than loud?",
    "What's the difference between confident and certain?",
    "When have you faked confidence and it worked?",
    "When have you faked it and it backfired?",
    "What kills confidence fastest in a conversation?",
    "What's the smallest move that signals you mean it?",
    "Is over-preparation a confidence move or a fear move?",
    "What's the line between confident and cocky?",
    "When does confidence become a problem?",
    "What makes someone sound green in the first ten seconds?",
    "What's the body part you control to sound sure?",
    "Why do people lose confidence mid-sentence?",
    "What does confidence look like when you don't know the answer?",
    "When is hesitation actually the strong move?",
    "What's the most confident thing you can do under fire?",
    "What's the strongest thing about admitting you don't know?",
    "How do you reset your voice after a wobble?",
    "What's the right way to walk into a room you're nervous about?",
    "What's a confidence tell you can't unsee?",
    "When does confidence become arrogance?",
    "What's the bridge between humility and authority?",
    "Why does pace matter more than volume here?",
    "What's the truest thing about nerves you've learned?",
    "How do you sound sure when you're not?",
    "What's the most overrated confidence move?",
    "What's underrated about pausing to think?",
    "When is it ok to walk something back without losing the room?",
    "Why do most 'fake it' tactics fail in week one?",
    "What's the cheapest way to look in control?",
    "What's the most expensive habit that signals weakness?",
  ],
  thinking_on_the_spot: [
    "What's the worst question to be asked cold?",
    "How do you buy time without sounding lost?",
    "What's your move when your brain freezes?",
    "When does saying 'good question' actually help?",
    "What's the cheapest way to think out loud cleanly?",
    "How do you stay calm when caught off guard?",
    "When is the honest 'I don't know' the right move?",
    "What's a phrase that buys you a beat?",
    "How do you avoid the rambling spiral?",
    "What's a question you've learned to dodge well?",
    "Why does the first answer often miss?",
    "When does pausing make you sound smarter?",
    "What's the truest thing about thinking on your feet?",
    "What's the difference between thinking out loud and stalling?",
    "How do you spot when you're losing the thread?",
    "What's the right way to backtrack mid-answer?",
    "When does a clean reset beat a long save?",
    "What's the move when you give a bad answer and know it?",
    "Why do most fast answers sound rehearsed?",
    "What's the question that catches everyone flat-footed?",
    "How do you keep your voice steady while your brain catches up?",
    "What's a habit that wrecks your composure under pressure?",
    "What's a habit that builds it?",
    "When did improv save you?",
    "When did over-preparation hurt you?",
    "What's a clean stall that doesn't feel like one?",
    "Why does naming the question help you answer it?",
    "What's underrated about silence in tough moments?",
    "How do you avoid hedging your way through?",
    "What's the line between thinking and stalling?",
    "When should you push back on the question instead of answering it?",
    "What's the best save you've ever made on the fly?",
  ],
  giving_feedback: [
    "What's the truest thing about feedback no one says out loud?",
    "Why is most feedback useless?",
    "What separates feedback that lands from feedback that fades?",
    "Is harsh feedback honest, or just easy?",
    "When does soft feedback do more harm than good?",
    "What's the best feedback you ever got — and why?",
    "What's the worst feedback you ever got — and why?",
    "Why does timing change everything?",
    "When is the right moment to say the hard thing?",
    "When is the wrong moment?",
    "What's the line between feedback and venting?",
    "How do you give feedback to someone trying their best?",
    "How do you give feedback to someone who isn't?",
    "What's the cheapest way to ruin good feedback?",
    "What's the move when feedback isn't being heard?",
    "Why does asking before telling work better?",
    "What's the right way to soften without softening the message?",
    "Is feedback a gift or a tax?",
    "When should you not give feedback at all?",
    "What's the difference between honest and brutal?",
    "Why do most feedback sandwiches taste stale?",
    "What's the move when feedback gets defensive in return?",
    "How do you give peer feedback without sounding like a boss?",
    "How do you give upward feedback without sounding like a complaint?",
    "What's underrated about specific, small feedback?",
    "What's overrated about big-picture feedback?",
    "When does writing it down beat saying it?",
    "When is in-person required?",
    "What do you do when you owe someone hard feedback and keep avoiding it?",
    "How do you give yourself feedback that actually changes something?",
    "Why does most feedback fail in the first sentence?",
  ],
  negotiation: [
    "What's the truest thing about negotiation that nobody teaches?",
    "Why does giving someone what they ask for sometimes lose the deal?",
    "What's the difference between negotiating and arguing?",
    "When does silence win a negotiation?",
    "What's the move when you don't have the leverage?",
    "What's the move when you do?",
    "What's worth trading and what isn't?",
    "When does walking away strengthen your position?",
    "What's the cheapest way to lose a negotiation?",
    "Why does over-explaining your price weaken it?",
    "What's the right way to anchor?",
    "When should you go first, when should you let them?",
    "What does a clean ask sound like?",
    "What does a clean no sound like?",
    "What's the move when both sides feel like they're losing?",
    "Why do most concessions get nothing in return?",
    "What's the difference between flexible and weak?",
    "When does friendliness work for you and when against?",
    "What's a question that resets a stuck negotiation?",
    "Why is BATNA more about your head than the deal?",
    "When does a small win matter more than a big one?",
    "What's the move when they say 'best and final'?",
    "What's the truest thing about deadlines?",
    "What's underrated about taking your time?",
    "What's the cleanest way to push back on a price?",
    "Why does the second offer usually beat the first?",
    "What's the move when there's no room left to give?",
    "When is splitting the difference the laziest answer?",
    "How do you negotiate when you also have to keep the relationship?",
    "What's the right way to bluff — and when not to?",
    "What's the line between firm and rigid?",
  ],
  presenting: [
    "What makes a presentation worth listening to?",
    "Why do most decks die in the first minute?",
    "What's the move in the first 30 seconds of any talk?",
    "What earns attention faster — energy or substance?",
    "What's the worst opening line in any presentation?",
    "What's the best opening you've ever heard?",
    "Why do most presenters under-stop?",
    "What's underrated about silence on stage?",
    "Is it better to be remembered or be liked?",
    "What's the cheapest way to lose a room?",
    "What's the cheapest way to win one?",
    "When does going off-script beat the slide?",
    "What's the move when the room's already bored?",
    "How do you open without 'thanks for having me'?",
    "What's a closing line that actually lands?",
    "Why does pace matter more than content?",
    "When do slides hurt instead of help?",
    "What's the truest thing about stage nerves?",
    "What does a confident presenter never do?",
    "Why does eye contact change the whole talk?",
    "What's the difference between presenting and lecturing?",
    "When does humor help, when does it cost you?",
    "How do you handle a hostile room?",
    "How do you handle an indifferent one?",
    "What's overrated in presentation training?",
    "What's underrated?",
    "What's the strongest move when tech fails?",
    "What's the move when you forget what you were saying?",
    "Why does the first slide matter more than the rest?",
    "What's the move when the room laughs at the wrong moment?",
  ],
  persuasion: [
    "What actually changes someone's mind?",
    "Why does logic alone rarely persuade?",
    "Why does giving someone what they ask for sometimes lose the deal?",
    "What's the truest thing about persuasion most pitches miss?",
    "Is curiosity more persuasive than certainty?",
    "When does pushing harder push them further away?",
    "What's the move when someone's already half-decided?",
    "What's underrated about listening as a persuasion move?",
    "When is the right time to make your strongest point?",
    "Why does the first claim get remembered most?",
    "What's the cheapest persuasion trick that still works?",
    "What's the most expensive habit that kills persuasion?",
    "When does walking away persuade?",
    "What's the difference between persuasion and manipulation?",
    "What does an honest pitch sound like?",
    "Why do most pitches lose in the first 30 seconds?",
    "What's underrated about taking the other side seriously?",
    "When does conceding a point win you the room?",
    "What's the right way to plant doubt?",
    "When does conviction work and when does it backfire?",
    "Why do most persuasive people listen more than they talk?",
    "What's the move when they say no twice?",
    "What's the move when they say maybe?",
    "Why does timing usually beat wording?",
    "When does silence persuade?",
    "What's the truest thing about why people buy?",
    "What's the truest thing about why they don't?",
    "What's the line between persuading and pushing?",
    "When is the soft sell the strong move?",
    "What's the move when someone wants to believe you but can't yet?",
  ],
  storytelling: [
    "What makes a story stick?",
    "What's a story you tell that's earned its keep?",
    "Why do most work stories fall flat?",
    "What's the truest thing about a story that actually moves people?",
    "When does a story persuade more than data?",
    "When is a story the wrong move?",
    "What's the right length for a story in a meeting?",
    "What's the move when you can feel the room losing interest?",
    "What's a small moment you keep coming back to?",
    "What makes you trust a storyteller?",
    "Why does the ending matter more than the setup?",
    "What's the strongest opening line for any story?",
    "What's the worst?",
    "Why do most storytellers over-explain?",
    "What's underrated about a story with no moral?",
    "When does specificity beat the big idea?",
    "What's a story you'd tell a younger version of yourself?",
    "What's a story you wouldn't tell at work and why?",
    "When did a story change your mind about something?",
    "What's the move when the story flops?",
    "What's a story everyone needs but few tell?",
    "Why does the first sentence decide whether they listen?",
    "What's the difference between a story and an anecdote?",
    "When does an anecdote work better than a full story?",
    "What's overrated about story structure?",
    "What's underrated about the small details?",
    "Why does a great story often skip the lesson?",
    "What's a story you tell that you've stopped believing?",
    "What's the move when you've told the same story too many times?",
    "Why is a clean ending harder than a clean opening?",
  ],
  asking_questions: [
    "What's the best question you've ever been asked?",
    "What's a question that opens a quiet room?",
    "What's a question worth asking in any meeting?",
    "What's the difference between a good question and a smart one?",
    "Why are most questions actually statements in disguise?",
    "When does a closed question beat an open one?",
    "What's a question you stopped asking — and wish you hadn't?",
    "What's the move when no one answers your question?",
    "What's a question you ask every day?",
    "Why does the second question usually beat the first?",
    "When is silence the right follow-up?",
    "What's the question that gets a real answer?",
    "What's the question that gets the safe one?",
    "When do you ask, when do you tell?",
    "What's the worst kind of question?",
    "What's a question that builds trust fast?",
    "What's a question that breaks it?",
    "Why do most leading questions sound desperate?",
    "What's the move when the room expects a question and you have none?",
    "What's the cleanest way to ask for what you want?",
    "What's overrated about open-ended questions?",
    "What's underrated about a yes/no question?",
    "When is the right time to ask the question you're afraid of?",
    "What's a question you ask yourself before any tough call?",
    "When does asking again work better than rephrasing?",
    "Why do follow-ups usually beat opening questions?",
    "What's the move when they dodge the question?",
    "What's the move when you dodge it?",
    "What's a question that's harder to ask than to answer?",
    "Why does curiosity outperform cleverness in questions?",
  ],
  explaining: [
    "What's something you understand that most people get wrong?",
    "What's the simplest way to say what you actually do?",
    "Why does over-explaining make things less clear?",
    "What's the truest thing about clarity nobody admits?",
    "When does an explanation make things worse?",
    "What's the difference between explaining and telling?",
    "What's the move when someone still doesn't get it?",
    "Why do most explanations start in the wrong place?",
    "What's the cheapest way to bore someone you're explaining to?",
    "What's the move when you're explaining something you only half know?",
    "Why do experts often explain things badly?",
    "What's the strongest opening for any explanation?",
    "When does an analogy beat a definition?",
    "When does a definition beat the analogy?",
    "What's underrated about checking if they followed?",
    "What's overrated about being thorough?",
    "When does saying less actually teach more?",
    "What's the move when the explanation runs long?",
    "What's the truest thing about jargon?",
    "Why does the second time you explain it usually go better?",
    "What's the right way to explain something obvious without sounding patronizing?",
    "When is a question a better explanation than an answer?",
    "What's the move when they ask you to repeat?",
    "Why does pace matter more than vocabulary?",
    "What's the difference between clear and dumbed down?",
    "What's the move when they pretend to understand?",
    "What's a clean test that your explanation landed?",
    "What's the cheapest way to lose someone mid-explanation?",
    "What's the move when you realize you're losing them?",
    "Why is one example usually better than three?",
  ],
};

// ============================================================================
// VERTICAL-LENSED B POOL — 30+ sales-themed universal moments per goal.
// These are about sales themes (deals, buyers, pitches, discovery, pipeline)
// without requiring a specific scene or imagined person.
// ============================================================================

const B_BY_GOAL = {
  handling_objections: [
    "Why do most pricing objections aren't really about price?",
    "What's the move when a prospect says 'we already have something'?",
    "When 'send me pricing' really means 'I'm not ready', what's the move?",
    "Why do most discount asks happen before value is set?",
    "What does it mean when a buyer says 'circle back in Q3'?",
    "Why do champions go quiet right before close?",
    "What's the truest thing about why deals slip late?",
    "When a buyer says 'too expensive', what are they really saying?",
    "Why does the second objection usually matter more than the first?",
    "When is 'no decision' the most dangerous answer in a deal?",
    "What does pushback from procurement actually mean?",
    "Why do legal redlines spike right before signature?",
    "What's the move when a deal stalls without a real reason?",
    "When the champion changes jobs mid-deal, what do you do?",
    "Why do most price objections get worse when you defend them?",
    "What's the truest thing about why prospects ghost?",
    "When 'we need to think about it' actually means no, how can you tell?",
    "Why does over-answering 'why now' weaken the answer?",
    "What's the move when a buyer keeps moving the goalposts?",
    "When does pushback signal real interest, not real resistance?",
    "What does 'we'll handle this internally' usually mean?",
    "Why do free trial requests often kill momentum?",
    "What's the move when the buyer wants more features than the price covers?",
    "When the economic buyer goes dark, what's the right next step?",
    "Why do most pricing concessions get nothing in return?",
    "What's the move when a deal's been re-scoped three times?",
    "Why does 'we just need approval' often mean no champion?",
    "What's the truest thing about why deals die in week 2?",
    "When pushback turns personal, how do you keep the deal alive?",
    "Why do most reps over-discount at the wrong moment?",
  ],
  confidence: [
    "What does a confident discovery call sound like?",
    "Where does a rep's confidence actually come from?",
    "Why do most reps wobble in the first 60 seconds of a call?",
    "What separates a rep who owns the room from one who survives it?",
    "When does selling under quota actually require more confidence, not less?",
    "What's the move when you walk into a call already behind plan?",
    "Why do most reps hedge their best line?",
    "What's the difference between confidence and a confident voice?",
    "What does a confident close sound like — without sounding pushy?",
    "Why do junior reps over-prepare and still freeze?",
    "What's underrated about admitting you don't know in a deal?",
    "When does confidence cross into arrogance with a buyer?",
    "What's the move when the buyer knows more about your product than you do?",
    "Why do most reps lose confidence right after the demo?",
    "What does it sound like when a rep believes the price?",
    "What does it sound like when they don't?",
    "Why do most reps apologize for follow-up?",
    "What's the truest thing about walking into a stretch deal?",
    "What does a clean ask for the meeting sound like?",
    "What does a clean ask for the close sound like?",
    "When does confidence make a small deal feel bigger than it is?",
    "What's the move when you're the youngest person on the call?",
    "Why do reps lose confidence when the buyer's quiet?",
    "What's the cheapest move that makes a rep look green?",
    "What's the move that makes them look senior?",
    "Why does pace matter more than tone on a hard call?",
    "When is a slow answer the most confident answer?",
    "What's the move when you blank on a key number?",
    "Why do most reps over-talk when they're nervous?",
    "What does it sound like to take a buyer seriously without flattering them?",
  ],
  thinking_on_the_spot: [
    "What's the move when a buyer asks you a number you don't know?",
    "How do you handle the curveball question on a demo?",
    "What's the move when discovery goes somewhere you didn't plan for?",
    "When a prospect surprises you with a competitor's offer, what do you do?",
    "What do you do when a buyer asks for a roadmap commitment you can't make?",
    "Why does the first answer on the fly usually undershoot?",
    "What's the move when the buyer pivots the meeting mid-call?",
    "How do you keep a discovery flowing when answers go thin?",
    "What's the truest thing about thinking on your feet in a deal?",
    "When you don't know an answer, what's the strongest move?",
    "Why does saying 'I'll get back to you' sometimes weaken trust?",
    "What's the move when a buyer asks about a feature you don't have?",
    "How do you handle a question about pricing before value is set?",
    "What's the move when your champion ambushes you with a hard ask?",
    "Why do most reps hedge when they should pause?",
    "When a buyer says 'tell me why I shouldn't go with X', what's the move?",
    "What's the right way to push back on a question you don't want to answer?",
    "How do you keep your composure when the call goes hostile?",
    "What's the move when a stakeholder you didn't expect joins the call?",
    "Why does silence work better than 'good question' here?",
    "What's the move when you misspoke earlier in the call?",
    "How do you steer back when a deal call gets derailed?",
    "What's the move when the buyer's question reveals a hole in your discovery?",
    "When a buyer says 'we have budget but no urgency', what do you do?",
    "What's the move when you realize mid-call this isn't your buyer?",
    "Why do most reps over-answer instead of clarify?",
    "What's the move when a buyer challenges your case study live?",
    "How do you keep selling when your demo glitches?",
    "What's the move when a buyer asks for a discount you can't approve?",
    "What's the move when you're caught flat-footed on a stat?",
  ],
  giving_feedback: [
    "What's the truest thing about feedback between reps?",
    "Why is most coaching feedback in sales useless?",
    "What's the move when you owe a peer hard feedback on a call?",
    "How do you give feedback to a rep who just lost a big deal?",
    "When should a manager not give feedback right after a call?",
    "What's the move when you have to give feedback to someone above quota?",
    "Why is feedback on tone so much harder to land than feedback on content?",
    "What's the right way to give feedback on a deal you didn't sit in on?",
    "What's the move when a rep keeps making the same mistake on calls?",
    "Why does waiting too long to give deal feedback waste it?",
    "What's the move when your boss gives you feedback you disagree with?",
    "How do you give upward feedback when forecast meetings go off?",
    "What's the cleanest way to give feedback on a discovery that missed?",
    "What's the move when a rep asks for feedback they're not ready for?",
    "Why does most sales coaching focus on the wrong moment in the call?",
    "What's the move when your CSM partner mis-handles a renewal call?",
    "What's the right way to push back on feedback from a manager?",
    "How do you give a rep feedback about a deal they're emotionally attached to?",
    "What's the move when a closed-lost deal is teaching the wrong lesson?",
    "Why do most pipeline reviews skip the feedback that matters?",
    "What's the move when a senior rep is coaching with old playbooks?",
    "How do you give a peer feedback without sounding like you're competing?",
    "What's the cleanest feedback for a rep over-discounting?",
    "What's the cleanest feedback for a rep under-asking?",
    "Why do most reps reject coaching from people who haven't sold?",
    "What's the move when feedback from a customer contradicts feedback from your boss?",
    "How do you give feedback on a deal that was won the wrong way?",
    "What's the right way to coach a rep through a slump?",
    "What's the move when a rep asks 'how would you have closed it'?",
    "Why does deal feedback often miss the moment it should have changed?",
  ],
  negotiation: [
    "Why does giving a discount before earning the right weaken it?",
    "What's the truest thing about price negotiations in B2B?",
    "When does silence win a sales negotiation?",
    "Why do most reps anchor too low?",
    "What's the move when procurement asks for 'best and final' too early?",
    "When is splitting the difference the laziest sales answer?",
    "What's the right way to push back on a discount ask without losing the deal?",
    "Why do most reps trade concessions without getting anything back?",
    "What's the move when the buyer says 'your competitor is 30% cheaper'?",
    "When does walking back terms strengthen your position?",
    "Why does naming your bottom line too early kill leverage?",
    "What's the move when a buyer slows negotiation just to grind you?",
    "What's the move when legal becomes the negotiator instead of the buyer?",
    "When does silence get you a better price than your script will?",
    "Why do most multi-year deals get negotiated badly in year one?",
    "What's the move when the buyer says 'we love it, just shave 20%'?",
    "Why does selling the value of price work better than defending price?",
    "What's the move when a buyer wants you to throw in services for free?",
    "When does conceding on terms beat conceding on price?",
    "Why does the second pricing round usually beat the first?",
    "What's the right move when a buyer says 'we'll sign today if…'?",
    "What's the move when procurement insists on a payment-term change?",
    "Why is anchoring before discovery a rookie move?",
    "What's the move when a buyer says 'we have budget for half that'?",
    "Why does giving them the win on a small term win you the deal?",
    "What's the move when a deal is stuck on one term you can't move?",
    "When does flexibility hurt instead of help?",
    "Why do most reps cave on first ask without thinking?",
    "What's the move when a buyer wants you to match a competitor's offer?",
    "Why does the rep with the most patience usually win the negotiation?",
  ],
  presenting: [
    "What's the move in the first 30 seconds of a sales pitch?",
    "Why do most demos die before the second click?",
    "What separates a sales presentation that closes from one that informs?",
    "Why do most sales decks have too many slides?",
    "What's the move when the buyer interrupts your pitch?",
    "What's the truest thing about why pitches lose in the first minute?",
    "Why does the second slide of a deck matter more than the first?",
    "When does going off-deck win the room?",
    "What's the move when a presentation to execs goes flat in 60 seconds?",
    "Why do most reps over-pitch and under-listen?",
    "What's the right opening line for any sales pitch?",
    "What's the move when the buyer pulls up their phone mid-demo?",
    "What's the move when the call has more silent stakeholders than expected?",
    "Why do most demos fail by trying to show everything?",
    "What's the move when you only have 5 minutes instead of 30?",
    "What's underrated about silence in a sales presentation?",
    "What's the cheapest pitch move that still loses deals?",
    "Why do most product demos miss the buyer's actual problem?",
    "What's the move when a deck looks bad on the buyer's laptop?",
    "Why does eye contact matter more than the slide?",
    "What's the move when an executive joins mid-pitch?",
    "What's the move when your screen share fails?",
    "Why does over-prepared often look under-confident in pitch?",
    "What's the move when the buyer says 'just skip to pricing'?",
    "Why do most reps under-rehearse the close of a pitch?",
    "What's the move when the call's been moved by 15 minutes?",
    "Why does pace matter more than content in a pitch?",
    "What's the move when a prospect joins late and asks you to restart?",
    "Why do most pitches treat the room as one person?",
    "What's the move when the buyer's already heard your pitch from someone else?",
  ],
  persuasion: [
    "Why do most pitches lose in the first 30 seconds?",
    "What actually changes a buyer's mind?",
    "Why does giving a buyer what they ask for sometimes lose the deal?",
    "What's the truest thing about why people buy from one rep over another?",
    "When is the soft sell the strong sell?",
    "What's the move when a buyer is half-decided already?",
    "Why does conviction outperform discounting in a tight deal?",
    "What's the move when a champion needs ammo to sell internally?",
    "Why do most reps over-pitch and under-trust the buyer?",
    "What's the move when the buyer's logic is right but their emotion isn't there?",
    "When does walking away persuade the deal forward?",
    "Why does the rep who listens longest usually close more?",
    "What's the move when a prospect needs your product but can't justify it yet?",
    "Why do most case studies fail to persuade?",
    "What's the right way to plant doubt about the competitor?",
    "When does conceding a small point win you the bigger one?",
    "What's the move when a buyer is convinced by data but not yet by you?",
    "What's the truest thing about why deals close on emotion, not logic?",
    "Why does urgency manufactured by the rep usually backfire?",
    "What's the move when the buyer trusts you but not your company?",
    "Why does asking 'what would change your mind' open more doors than pushing?",
    "What's the move when the economic buyer is the hardest to persuade?",
    "When does silence persuade in a closing call?",
    "Why do most cold outreach pitches sound like everyone else's?",
    "What's the move when a buyer says 'we believe in you but…'?",
    "Why does the second meeting persuade more than the first?",
    "What's the move when the buyer says 'we just need to align internally'?",
    "Why do most reps over-rely on logic in a pitch and miss the emotion?",
    "What's the move when a buyer keeps saying they love it but won't sign?",
    "Why does the rep who tells the truest story usually win?",
  ],
  storytelling: [
    "What's a customer story you'd tell on any first call?",
    "Why do most case studies fail to tell a story?",
    "What's the truest thing about why customer stories beat features?",
    "What's the move when your case study doesn't match the buyer's situation?",
    "Why do most reps tell the same customer story too many times?",
    "What's the right length for a customer story in a discovery call?",
    "What's the strongest opening line for a sales story?",
    "What's a small detail in a customer story that earns trust fast?",
    "Why does specificity in a story beat the big results number?",
    "What's the move when the buyer says 'we're not like that company'?",
    "Why do most reps tell stories about wins instead of the harder middle?",
    "What's the move when a buyer asks for a story you don't have a perfect match for?",
    "What's a story you tell about a deal you lost — and what it taught you?",
    "Why does the ending of a sales story matter more than the setup?",
    "What's the move when your big customer logo isn't moving the buyer?",
    "Why do most sales stories skip the part that makes them believable?",
    "What's the truest thing about why founder stories outsell product stories?",
    "What's the move when you're selling to a company that's never bought anything like this?",
    "Why does a story about a buyer who almost said no land harder than one about an easy yes?",
    "What's a story you'd tell a new rep on their first day?",
    "What's a story that earned you trust faster than a demo would have?",
    "Why do most reps under-tell the moment the customer hit a real problem?",
    "What's the move when the customer story sounds rehearsed?",
    "What's underrated about a story that takes longer than 60 seconds?",
    "Why does a story about a failed implementation often sell better than a flawless one?",
    "What's the move when a buyer interrupts your story?",
    "Why does telling the story of how you came to believe in your product earn more than the pitch?",
    "What's the move when a story you've told many times stops landing?",
    "What's a story you tell yourself to keep going through a tough quarter?",
    "Why does a story that admits a flaw usually outperform one that doesn't?",
  ],
  asking_questions: [
    "What's the best question you've asked on a discovery call?",
    "What's a question that opens up a quiet buyer?",
    "Why are most discovery questions actually statements in disguise?",
    "What's the difference between a discovery question and a qualification one?",
    "Why does the second question on a call usually matter more than the first?",
    "What's the question that gets a real answer about budget?",
    "What's the question that gets a real answer about timeline?",
    "Why do most reps ask 'what's your budget' the wrong way?",
    "What's the move when the buyer dodges your discovery question?",
    "What's a question you ask before every executive call?",
    "Why do follow-up questions usually beat scripted ones?",
    "What's the question that uncovers the real decision maker?",
    "What's the question that uncovers the real timeline?",
    "Why do most reps stop asking too early?",
    "What's the question that pulls out the buyer's quiet objection?",
    "What's the move when a buyer answers in one word?",
    "Why does asking 'what would have to be true' open up planning?",
    "What's the question that exposes a deal isn't real?",
    "Why do most discovery decks ask too many questions?",
    "What's the question that earns a champion's loyalty?",
    "When does asking the obvious question work best?",
    "Why do most reps fear asking 'why now'?",
    "What's the question that gets a real answer about competition?",
    "What's the move when the room is quiet and your script is out?",
    "Why does silence after a question pull more than rephrasing?",
    "What's a question that turns a stalled deal into a real one?",
    "What's a question that no rep on your team is asking but should?",
    "What's the question that gets the buyer thinking about your problem differently?",
    "Why do most reps ask 'are you happy with your current solution' too cheaply?",
    "What's the move when the buyer asks more questions than you do?",
  ],
  explaining: [
    "What's the move when a buyer doesn't get what your product actually does?",
    "Why do most reps over-explain the product and under-explain the value?",
    "What's the cleanest way to explain your pricing model?",
    "What's the truest thing about why most sales explanations bore people?",
    "Why does explaining like the buyer's smart usually outperform explaining like they're new?",
    "What's the move when the buyer asks 'what makes you different' and you've answered it 100 times?",
    "What's the cleanest explanation of how your product saves a buyer time?",
    "What's the cleanest explanation of how it saves money?",
    "Why do most product explanations bury the lead?",
    "What's the move when explaining a technical concept to a non-technical buyer?",
    "Why do most reps explain features when they should be explaining outcomes?",
    "What's the strongest 30-second explanation of what your company does?",
    "What's the move when a buyer asks you to explain again?",
    "What's the move when the buyer says 'I still don't get it'?",
    "Why does pace matter more than vocabulary on a hard explanation?",
    "What's the move when an analogy fails mid-call?",
    "Why do most reps explain ROI badly?",
    "What's the cleanest way to explain why you cost more than the competitor?",
    "What's the move when explaining a roadmap commitment you can't fully make?",
    "Why does a one-sentence explanation usually beat a five-slide one?",
    "What's the move when explaining your security posture to a buyer's IT?",
    "What's the cleanest way to explain your implementation timeline?",
    "Why do most onboarding explanations terrify buyers instead of reassuring them?",
    "What's the move when the buyer asks you to explain a feature you don't love?",
    "Why is explaining what you don't do as important as what you do?",
    "What's the move when explaining your tier structure to a budget-conscious buyer?",
    "Why does the second explanation in a deal usually land better than the first?",
    "What's the cleanest explanation of how your renewal works?",
    "What's the move when a champion asks you for words they can use internally?",
    "Why does explaining the 'why' before the 'what' work better in sales?",
  ],
};

// ============================================================================
// LIGHT SCENARIO C POOL — 30+ light situations per goal.
// These are KIND-of situations any sales rep encounters regularly.
// No specific people, no specific company. Anyone in sales recognizes them.
// ============================================================================

const C_BY_GOAL = {
  handling_objections: [
    "Push back on a buyer who keeps moving the goalposts — without losing the deal.",
    "Respond to 'send me pricing' without just sending pricing.",
    "Push back on a buyer who says 'we'll handle it internally' — honestly.",
    "Respond to 'your competitor is cheaper' without dropping price.",
    "Push back on a champion who's losing momentum.",
    "Respond to 'we just need a few more weeks' — for the third time.",
    "Push back when a buyer wants every feature but won't commit on budget.",
    "Respond to a buyer who says they don't see the value — yet.",
    "Push back on a buyer asking for a custom feature that doesn't make sense.",
    "Respond to 'we love it but not now' without giving up the deal.",
    "Push back on a procurement lead asking for an unreasonable term.",
    "Respond to a buyer who keeps inviting more stakeholders into the deal.",
    "Push back on a deal that's been re-scoped three times.",
    "Respond to a champion who's gone quiet for a week.",
    "Push back on a stretch ask without crushing the relationship.",
    "Respond to a buyer who wants free services to close.",
    "Push back on a legal redline that changes the risk profile of the deal.",
    "Respond to a buyer who thinks the contract is too long.",
    "Push back on a buyer who keeps testing 'best price'.",
    "Respond to a buyer who says your case studies don't match them.",
    "Push back on a buyer who asks 'can you do this for half'?",
    "Respond to a champion who's lost their internal sponsor.",
    "Push back on a buyer who says 'we'd buy if you weren't a startup'.",
    "Respond to a buyer who asks for a multi-year guarantee.",
    "Push back when the deal isn't moving and you don't know why.",
    "Respond to a buyer who says 'this isn't a priority right now'.",
    "Push back when the buyer wants to delay implementation indefinitely.",
    "Respond to a buyer who says you're overpromising.",
    "Push back when an executive joins the deal late with a hard ask.",
    "Respond to a buyer who says 'we don't see the urgency'.",
  ],
  confidence: [
    "Open a first discovery call without sounding green.",
    "Walk into a deal already behind plan without showing it.",
    "Open a stretch deal call like you've been doing this for years.",
    "Walk into a call with someone three levels above you and own the room.",
    "Open a renewal conversation without sounding defensive.",
    "Walk into a pricing call without flinching at the number.",
    "Open a hard discovery call with a buyer who interrupts.",
    "Walk into a demo with a quiet group and pull energy out of them.",
    "Open a follow-up call after the buyer ghosted you.",
    "Walk into a competitive deal already late in the cycle.",
    "Open a call with a procurement lead who's just trying to grind you.",
    "Walk into a deal where the buyer knows your product better than you do.",
    "Open a kickoff call after a deal closed on tight terms.",
    "Walk into a deal you inherited from another rep.",
    "Open the close conversation without softening the ask.",
    "Walk into a quarterly business review with bad numbers.",
    "Open a pitch to a board with one slide and nothing else.",
    "Walk into a deal that's 50% bigger than anything you've closed.",
    "Open a call where the prospect already said no once.",
    "Walk into an exec briefing when you're the only rep in the room.",
    "Open a renewal call after a customer's been struggling.",
    "Walk into the buyer's office the day after a service outage.",
    "Open a call with a buyer who's been to a competitor's demo this week.",
    "Walk into a deal review with leadership when you've slipped two quarters.",
    "Open a pricing conversation with a buyer who knows your discount band.",
    "Walk into a call ten minutes before your number is due.",
    "Open a tough renewal where pricing went up.",
    "Walk into a call where you're 90 days into the role.",
    "Open the close ask on a deal that's bigger than your last five combined.",
    "Walk into a deal where the buyer's already negotiating with two competitors.",
  ],
  thinking_on_the_spot: [
    "A buyer asks for a number you don't have. Answer.",
    "A demo glitches mid-call. Keep selling.",
    "A buyer asks 'what makes you different' and you've heard it 1,000 times. Answer fresh.",
    "A stakeholder you didn't expect joins the call. Adjust.",
    "A buyer asks about a feature you don't have. Answer honestly.",
    "Discovery goes off-script. Steer it back.",
    "A buyer asks about a roadmap commitment. Answer without overpromising.",
    "A buyer asks about an outage they saw on Twitter. Answer.",
    "The buyer pulls up their phone mid-pitch. Recover.",
    "An executive jumps in mid-call with a hard question. Answer.",
    "A buyer asks you to compare yourself to a competitor you barely know.",
    "A buyer asks 'why should I trust you'. Answer honestly, fast.",
    "A buyer asks about your churn rate. Answer.",
    "A buyer asks for an unreasonable discount. Respond without flinching.",
    "Your champion ambushes you with a new stakeholder. Adjust.",
    "A demo question goes deep into edge cases. Stay clean.",
    "A buyer says 'just give me the gist' five minutes into the demo. Pivot.",
    "A buyer questions a case study live. Answer.",
    "A buyer asks why your last competitor lost the deal. Answer.",
    "A buyer reframes the problem mid-call. Follow them.",
    "A buyer asks about pricing before you've earned the right. Handle it.",
    "An executive asks 'what's the one thing I should know'. Answer.",
    "A buyer asks for a reference and you don't have a perfect match. Respond.",
    "A buyer says 'I have ten minutes'. Re-plan in real time.",
    "Your prospect's CFO joins late. Catch them up in a sentence.",
    "A buyer asks 'why now' and your usual answer doesn't fit. Answer.",
    "A buyer challenges your security posture on the call. Answer.",
    "A buyer asks 'what's your worst customer story'. Answer.",
    "A buyer changes the meeting purpose 30 seconds in. Adjust.",
    "A buyer asks you to compare your roadmap to a competitor's. Answer.",
  ],
  giving_feedback: [
    "Give a peer feedback on a discovery call that missed.",
    "Tell a rep their pitch is losing energy in the middle.",
    "Give your manager feedback on a deal review that wasn't useful.",
    "Tell a rep on your team they're discounting too early.",
    "Give a CSM feedback on a renewal call that lost the customer.",
    "Tell a rep they're not asking enough discovery questions.",
    "Give a peer feedback on a deal they over-engineered.",
    "Tell a junior rep their close ask is too soft.",
    "Give your boss feedback on the forecast process.",
    "Tell a rep their pitch is too feature-heavy.",
    "Give a peer feedback on a deal that closed for the wrong reason.",
    "Tell a senior rep their playbook is dated.",
    "Give a rep feedback on a lost deal they still think was winnable.",
    "Tell a manager their pipeline review is missing the real signal.",
    "Give a rep feedback on a demo that didn't land.",
    "Tell a peer their tone with a prospect was off.",
    "Give a colleague feedback on a deal they walked away from too early.",
    "Tell a rep they're chasing the wrong champion.",
    "Give feedback to a teammate who keeps cutting in on calls.",
    "Tell a rep their forecast is too optimistic.",
    "Give a rep feedback on a deal they're emotionally attached to.",
    "Tell a peer their cold outreach is sounding too templated.",
    "Give a CSM feedback on the way they handle escalations.",
    "Tell a rep their stretch deal isn't real.",
    "Give a manager feedback on the deal stages they're using.",
    "Tell a peer their objection handling needs work.",
    "Give a rep feedback on the way they close a meeting.",
    "Tell a senior rep their case study is no longer landing.",
    "Give a rep feedback after they lost a deal they should have won.",
    "Tell a peer their discovery is too procurement-focused.",
  ],
  negotiation: [
    "Negotiate a deal where the buyer wants a 30% discount.",
    "Negotiate when procurement says 'best and final'.",
    "Negotiate a multi-year commitment with a buyer worried about flexibility.",
    "Negotiate when the buyer wants free services thrown in.",
    "Negotiate a payment-term change without losing margin.",
    "Negotiate when the buyer says your competitor is cheaper.",
    "Negotiate a renewal with a price increase the customer didn't expect.",
    "Negotiate a deal where the buyer needs to come in at a round number.",
    "Negotiate when the buyer wants to drop a tier mid-cycle.",
    "Negotiate a stretch deal where margin is thin.",
    "Negotiate when the buyer asks for an opt-out clause.",
    "Negotiate when the buyer wants a custom SLA you can't fully match.",
    "Negotiate when the buyer wants you to absorb a third-party fee.",
    "Negotiate when the buyer's procurement insists on a security exception.",
    "Negotiate when the buyer wants longer payment terms.",
    "Negotiate when the buyer wants a clause that hurts on year two.",
    "Negotiate when the buyer says they're walking unless you move.",
    "Negotiate when a champion gets pulled and a new buyer reopens terms.",
    "Negotiate when the buyer wants you to match an outdated competitor offer.",
    "Negotiate when the buyer wants migration costs covered.",
    "Negotiate when the buyer wants a 90-day out clause.",
    "Negotiate when legal redlines change the risk on your side.",
    "Negotiate when the buyer's CFO joins the call with a new number.",
    "Negotiate when the buyer wants a discount in exchange for a logo right.",
    "Negotiate when the buyer wants to split the order across two business units.",
    "Negotiate when the buyer says they can only sign at half the seats.",
    "Negotiate when the buyer wants a multi-year price lock.",
    "Negotiate when the buyer wants a guaranteed roadmap delivery.",
    "Negotiate when the buyer wants a non-standard contract template.",
    "Negotiate when the buyer asks for a side letter on top of the MSA.",
  ],
  presenting: [
    "Open a sales pitch when the room hasn't bought into the meeting yet.",
    "Pitch your product to a buyer who's already seen two competitors this week.",
    "Open a demo when you only have 5 minutes instead of 30.",
    "Pitch to a room where the buyer's CFO joined late.",
    "Open a renewal QBR with mixed results.",
    "Pitch to a buyer who already said no once.",
    "Open a call when the buyer says 'just skip to pricing'.",
    "Pitch to an executive who's clearly multitasking.",
    "Open a deck when your first slide misloads.",
    "Pitch to a room of silent stakeholders you weren't expecting.",
    "Open a demo when a feature you wanted to show isn't working.",
    "Pitch your value when the buyer interrupts with 'we already know this'.",
    "Open a board pitch with one minute on the clock.",
    "Pitch to a hostile room that already has a preferred vendor.",
    "Open a fresh pitch to a customer who's seen yours three times before.",
    "Pitch when your screen share fails and you have to go without slides.",
    "Open a customer pitch when the buyer's strategy just changed.",
    "Pitch to a room of buyers who joined for different reasons.",
    "Open a renewal pitch where last year had service issues.",
    "Pitch a product update to a customer who's already frustrated.",
    "Open a kickoff call where the customer feels they paid too much.",
    "Pitch to a stakeholder you've never met who joined the call cold.",
    "Open a deck that's been used by everyone on your team — fresh.",
    "Pitch when the buyer's competitor is already in their stack.",
    "Open a call where the buyer says 'I have ten minutes'.",
    "Pitch to a buyer whose own team is divided on the decision.",
    "Open a follow-up pitch after a deal stalled for three weeks.",
    "Pitch to a buyer who wants the technical detail before the value.",
    "Open a final pitch on the close call.",
    "Pitch to a room when your champion's already pitching for you.",
  ],
  persuasion: [
    "Persuade a buyer who's already half-decided against you.",
    "Persuade a buyer who trusts you but not your company.",
    "Persuade a champion to push your deal up the priority list.",
    "Persuade a buyer to take a meeting with their CFO sooner.",
    "Persuade an economic buyer who has no time for the demo.",
    "Persuade a buyer to expand seats at renewal.",
    "Persuade a buyer to pick the higher tier.",
    "Persuade a buyer to give you a reference call.",
    "Persuade a buyer to introduce you to another team.",
    "Persuade a buyer to take a multi-year commitment.",
    "Persuade a champion who's gone quiet to re-engage.",
    "Persuade a buyer who keeps saying 'we'll think about it'.",
    "Persuade an exec to show up to the close call.",
    "Persuade a CSM-side stakeholder to advocate for you.",
    "Persuade a procurement team to fast-track the deal.",
    "Persuade a buyer who's anchored on a competitor.",
    "Persuade a CFO who's never bought your category before.",
    "Persuade a buyer who's been burned by a similar vendor.",
    "Persuade a buyer to take a smaller pilot now and expand later.",
    "Persuade a champion to fight for a contract clause internally.",
    "Persuade a buyer who's afraid of switching costs.",
    "Persuade a buyer who's afraid of internal politics.",
    "Persuade a buyer who's afraid of a board pushback.",
    "Persuade a buyer to sign by end of quarter without sounding desperate.",
    "Persuade a buyer who's worried about implementation time.",
    "Persuade a buyer who's worried about training their team.",
    "Persuade a buyer who keeps saying 'we love it but not now'.",
    "Persuade a champion to forward your one-pager up.",
    "Persuade a buyer to take a call when they've cancelled twice.",
    "Persuade a buyer who's quietly already picked you to actually sign.",
  ],
  storytelling: [
    "Tell a story about a customer who almost said no — and didn't.",
    "Tell a story about a deal you lost and what it taught you.",
    "Tell a story about a customer who solved a hard problem with your product.",
    "Tell a story about a customer who took a chance on you early.",
    "Tell a story about a customer where adoption took longer than expected.",
    "Tell a story about a customer who became a champion.",
    "Tell a story about a customer who almost churned and stayed.",
    "Tell a story about a customer whose results were better than expected.",
    "Tell a story about a customer whose results were worse — and what you did.",
    "Tell a story about a deal that closed because of a small detail.",
    "Tell a story about a champion who lost a battle internally.",
    "Tell a story about why you joined this company.",
    "Tell a story about a deal you almost walked away from.",
    "Tell a story about a customer call that changed how you sell.",
    "Tell a story about a competitor deal you won — and why.",
    "Tell a story about a customer onboarding that went sideways and back.",
    "Tell a story about a customer who pushed your product into a new use case.",
    "Tell a story about a customer who took a pricing risk on you.",
    "Tell a story about a customer whose CFO became the champion.",
    "Tell a story about a deal you're not allowed to talk about — without naming them.",
    "Tell a story about a customer where the first demo flopped.",
    "Tell a story about a deal that died and came back six months later.",
    "Tell a story about a customer who asked for the impossible — and got something close.",
    "Tell a story about a tough buyer who turned into a fan.",
    "Tell a story about a customer who taught you something you didn't expect.",
    "Tell a story about a deal where you broke a personal rule.",
    "Tell a story about a customer who pushed you to do better work.",
    "Tell a story about a customer call you wish you could redo.",
    "Tell a story about a customer who almost made the wrong choice.",
    "Tell a story about a customer who taught your whole team something.",
  ],
  asking_questions: [
    "Ask the discovery question that opens up the real problem.",
    "Ask the question that uncovers the real decision maker.",
    "Ask the question that exposes whether this deal is real.",
    "Ask the question that gets a real answer about timeline.",
    "Ask the question that gets a real answer about budget — without naming budget.",
    "Ask the question that surfaces a champion's internal blockers.",
    "Ask the question that earns a buyer's trust on a first call.",
    "Ask the question that gets a quiet buyer to talk.",
    "Ask the question that turns a 'maybe' into a 'why'.",
    "Ask the question that exposes a competitor's weakness without naming them.",
    "Ask the question that gets the buyer talking about their KPIs.",
    "Ask the question that reveals a buyer's real motivation.",
    "Ask the question that surfaces the executive sponsor.",
    "Ask the question that exposes whether procurement is a friend or foe.",
    "Ask the question that gets a renewal conversation moving.",
    "Ask the question that pulls a stalled deal back into motion.",
    "Ask the question that gets a champion to fight for you.",
    "Ask the question that gets the buyer thinking about urgency.",
    "Ask the question that exposes a quiet objection.",
    "Ask the question a senior rep would ask on a first call.",
    "Ask the question that opens up the buyer's politics.",
    "Ask the question that gets the buyer to do the math out loud.",
    "Ask the question that reveals what 'success' means to the buyer.",
    "Ask the question that exposes a missing stakeholder.",
    "Ask the question that exposes a real competitor in the deal.",
    "Ask the question that helps the buyer build a business case.",
    "Ask the question that exposes whether the buyer has authority.",
    "Ask the question that helps the buyer sell internally for you.",
    "Ask the question that earns more time in the next meeting.",
    "Ask the question that reframes the buyer's problem.",
  ],
  explaining: [
    "Explain your pricing model to a buyer hearing it for the first time.",
    "Explain how your product saves time, in plain words.",
    "Explain how your product saves money, without using a calculator.",
    "Explain your differentiator without naming the competitor.",
    "Explain your security posture to a non-technical buyer.",
    "Explain your onboarding process to a nervous buyer.",
    "Explain your renewal process in one paragraph.",
    "Explain your roadmap commitment without overpromising.",
    "Explain why you cost more than the competitor.",
    "Explain your usage-based pricing to a buyer used to flat fees.",
    "Explain a feature you don't love — honestly.",
    "Explain why your product doesn't solve their specific edge case — and what you do solve.",
    "Explain why your trial doesn't tell the whole story.",
    "Explain how your services package works.",
    "Explain your customer success model in plain terms.",
    "Explain your SLA without using SLA-language.",
    "Explain why your contract is the length it is.",
    "Explain why you're a startup, without sounding defensive.",
    "Explain your churn story honestly.",
    "Explain why a competitor's feature isn't on your roadmap.",
    "Explain how your team grew over the last year — and why that matters to the buyer.",
    "Explain your tier structure to a budget-conscious buyer.",
    "Explain your scope of services without sounding limiting.",
    "Explain a 'we can't do that' answer without losing the deal.",
    "Explain your renewal pricing increase to a happy customer.",
    "Explain why discounting now hurts them later.",
    "Explain a complex integration to a non-engineer.",
    "Explain how implementation works without scaring the buyer.",
    "Explain your reference customer's results without exaggerating.",
    "Explain to a champion the words to use with their CFO.",
  ],
};

// ============================================================================
// Build prompts: pick one A, one B, one C per (exercise, goal) using diagonal
// indexing for variety across exercises (a different position in the pool for
// each exercise).
// ============================================================================

function trim180(t) {
  let s = (t || "").trim();
  if (s.length > 180) s = s.slice(0, 178).trimEnd() + "…";
  return s;
}

function pick(pool, exIdx, goalIdx) {
  // Diagonal pick across exercises so the same goal gets different prompts
  // for different exercises. Stride = 3 to avoid collisions in small pools.
  return pool[(exIdx * 3 + goalIdx) % pool.length];
}

function build(targets) {
  const seen = new Set();
  const inserts = [];
  for (const [exIdx, exName] of targets.entries()) {
    const list = [];
    for (const [goalIdx, goal] of GOALS.entries()) {
      const aPool = A_BY_GOAL[goal];
      const bPool = B_BY_GOAL[goal];
      const cPool = C_BY_GOAL[goal];
      const aText = pick(aPool, exIdx, goalIdx);
      const bText = pick(bPool, exIdx, goalIdx);
      const cText = pick(cPool, exIdx, goalIdx);
      const triples = [
        { text: aText, difficulty: archDiff("A", exIdx, goalIdx) },
        { text: bText, difficulty: archDiff("B", exIdx, goalIdx) },
        { text: cText, difficulty: archDiff("C", exIdx, goalIdx) },
      ];
      for (const tr of triples) {
        let text = trim180(tr.text);
        let key = text.toLowerCase();
        if (seen.has(key)) {
          // Disambiguate by appending goal nuance, keeping under 180.
          const suffix = ` — on ${goal.replace(/_/g, " ")}`;
          text = trim180(text + suffix);
          key = text.toLowerCase();
          // If still collision, drop a tiny exercise hint
          if (seen.has(key)) {
            const suffix2 = ` (${exName.toLowerCase()})`;
            text = trim180(text + suffix2);
            key = text.toLowerCase();
          }
        }
        seen.add(key);
        list.push({ text, difficulty: tr.difficulty, tags: ["sales", goal] });
      }
    }
    inserts.push({ name: exName, prompts: list });
  }
  return inserts;
}

// ============================================================================
// Load catalog. Identify first 27 exercises (sorted by dimension+name).
// Append new prompts. Disambiguate against existing texts. Write back.
// ============================================================================

const catalog = JSON.parse(fs.readFileSync(CATALOG_PATH, "utf8"));

const sorted = [...catalog.exercises]
  .map(e => ({ dimension: e.dimension, name: e.name }))
  .sort((a, b) => a.dimension.localeCompare(b.dimension) || a.name.localeCompare(b.name));

const TARGETS = sorted.slice(0, 27).map(s => s.name);
console.log("Target exercises (first 27):");
sorted.slice(0, 27).forEach((s, i) => console.log(`  ${i + 1}. ${s.dimension} | ${s.name}`));

// Build authored prompts
const inserts = build(TARGETS);

// Dedup against existing catalog texts
const existingText = new Set();
for (const ex of catalog.exercises) {
  for (const p of ex.prompts) existingText.add(p.text.toLowerCase().trim());
}

let collisions = 0;
for (const ins of inserts) {
  const catEx = catalog.exercises.find(e => e.name === ins.name);
  if (!catEx) {
    console.error("MISSING exercise in catalog:", ins.name);
    process.exit(1);
  }
  for (const p of ins.prompts) {
    const key = p.text.toLowerCase().trim();
    if (existingText.has(key)) {
      const goalTag = p.tags.find(t => t !== "sales") || "sales";
      const suffix = ` — on ${goalTag.replace(/_/g, " ")}`;
      p.text = trim180(p.text + suffix);
      if (existingText.has(p.text.toLowerCase().trim())) {
        const suffix2 = ` (${ins.name.toLowerCase()})`;
        p.text = trim180(p.text + suffix2);
      }
      collisions++;
    }
    existingText.add(p.text.toLowerCase().trim());
    catEx.prompts.push(p);
  }
}

// Difficulty stats
const allNew = inserts.flatMap(i => i.prompts);
const counts = { intro: 0, core: 0, stretch: 0 };
for (const p of allNew) counts[p.difficulty]++;
console.log("\nExercises authored:", inserts.length);
console.log("Prompts authored:", allNew.length);
console.log("Triples covered:", allNew.length / 3);
console.log("Difficulty:", counts);
console.log("Pct intro/core/stretch:",
  (counts.intro / allNew.length * 100).toFixed(1) + "%",
  (counts.core / allNew.length * 100).toFixed(1) + "%",
  (counts.stretch / allNew.length * 100).toFixed(1) + "%");
console.log("Collisions resolved:", collisions);

// Length checks
const lengths = allNew.map(p => p.text.length);
console.log("Max length:", Math.max(...lengths));
console.log("Avg length:", Math.round(lengths.reduce((s, n) => s + n, 0) / lengths.length));

// Sample prompts for report
console.log("\n--- SAMPLES ---");
const sampleEx = inserts[0];
console.log("Exercise:", sampleEx.name);
console.log("A (universal craft):", sampleEx.prompts[0].text);
console.log("B (sales-lens):", sampleEx.prompts[1].text);
console.log("C (scenario):", sampleEx.prompts[2].text);
const stretchSample = allNew.find(p => p.difficulty === "stretch");
console.log("Stretch sample:", stretchSample ? stretchSample.text : "(none)");

// Write
fs.writeFileSync(CATALOG_PATH, JSON.stringify(catalog, null, 2) + "\n", "utf8");
console.log("\nWrote", CATALOG_PATH);
